"""
Curated database of the most frequent German adjectives and adverbs with prepositions.
Organized by frequency and CEFR level (A1 to C1).

Every entry includes:
- adj_group: Root adjective for grouping related variations
- adjective: Display adjective form
- prep: The required preposition
- case: "+ Akk.", "+ Dat.", "+ Gen.", "+ Nom."
- case_type: "akk", "dat", "gen", "nom"
- meaning_en: Meaning of this specific adjective + preposition combination
- sentence_de: German example sentence with {PREP} placeholder
- sentence_en: English translation of sentence
- question_structure: Da-/Wo- compound for things and prepositional question for people
- level: CEFR level (A1, A2, B1, B2, C1)
- grammar_notes: Practical usage advice, nuances, contrasts
- adj_rank: Relative frequency rank
"""

RAW_ADJECTIVE_DATA = [
    # ==========================================
    # TIER 1: Highly frequent foundation (A1 - A2)
    # ==========================================
    {
        "adj_group": "zufrieden",
        "adjective": "zufrieden",
        "prep": "mit",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "satisfied with / content with",
        "sentence_de": "Der Chef ist sehr zufrieden {PREP} deinen guten Arbeitsergebnissen.",
        "sentence_en": "The boss is very satisfied with your good work results.",
        "question_structure": "Womit? • Damit / Mit wem?",
        "level": "A1",
        "grammar_notes": "Always takes 'mit + Dativ'. Essential everyday expression.",
        "adj_rank": 1,
    },
    {
        "adj_group": "zufrieden",
        "adjective": "unzufrieden",
        "prep": "mit",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "dissatisfied with / unhappy with",
        "sentence_de": "Viele Kunden sind unzufrieden {PREP} dem langsamen Service.",
        "sentence_en": "Many customers are dissatisfied with the slow service.",
        "question_structure": "Womit? • Damit / Mit wem?",
        "level": "A2",
        "grammar_notes": "Antonym of 'zufrieden mit'. Takes 'mit + Dativ'.",
        "adj_rank": 1,
    },
    {
        "adj_group": "stolz",
        "adjective": "stolz",
        "prep": "auf",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "proud of",
        "sentence_de": "Die Eltern sind unheimlich stolz {PREP} ihre fleißige Tochter.",
        "sentence_en": "The parents are incredibly proud of their hardworking daughter.",
        "question_structure": "Worauf? • Darauf / Auf wen?",
        "level": "A2",
        "grammar_notes": "Always takes 'auf + Akkusativ'. Never 'von'!",
        "adj_rank": 2,
    },
    {
        "adj_group": "wichtig",
        "adjective": "wichtig",
        "prep": "für",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "important for / to",
        "sentence_de": "Ausreichend Schlaf ist enorm wichtig {PREP} die Konzentration.",
        "sentence_en": "Sufficient sleep is enormously important for concentration.",
        "question_structure": "Wofür? • Dafür / Für wen?",
        "level": "A1",
        "grammar_notes": "Takes 'für + Akkusativ' (or a plain Dativ pronoun: 'Das ist mir wichtig').",
        "adj_rank": 3,
    },
    {
        "adj_group": "interessiert",
        "adjective": "interessiert",
        "prep": "an",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "interested in",
        "sentence_de": "Sind Sie {PREP} einem unverbindlichen Beratungsgespräch interessiert?",
        "sentence_en": "Are you interested in a non-binding consultation?",
        "question_structure": "Woran? • Daran",
        "level": "A2",
        "grammar_notes": "ATTENTION: 'interessiert sein an + Dativ' vs. the verb 'sich interessieren für + Akkusativ'!",
        "adj_rank": 4,
    },
    {
        "adj_group": "dankbar",
        "adjective": "dankbar",
        "prep": "für",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "grateful for / thankful for",
        "sentence_de": "Ich bin dir unendlich dankbar {PREP} deine uneigennützige Hilfe.",
        "sentence_en": "I am endlessly grateful to you for your unselfish help.",
        "question_structure": "Wofür? • Dafür",
        "level": "A2",
        "grammar_notes": "Formula: jemandem (Dat) für etwas (Akk) dankbar sein.",
        "adj_rank": 5,
    },
    {
        "adj_group": "böse",
        "adjective": "böse",
        "prep": "auf",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "angry with / mad at (a PERSON)",
        "sentence_de": "Bist du immer noch böse {PREP} deinen kleinen Bruder?",
        "sentence_en": "Are you still mad at your little brother?",
        "question_structure": "Auf wen?",
        "level": "A2",
        "grammar_notes": "Directed at a person: 'auf + Akkusativ'.",
        "adj_rank": 6,
    },
    {
        "adj_group": "böse",
        "adjective": "böse",
        "prep": "über",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "upset about / angry about (a SITUATION or outcome)",
        "sentence_de": "Er war sehr böse {PREP} die unnötige Niederlage im Spiel.",
        "sentence_en": "He was very upset about the unnecessary defeat in the game.",
        "question_structure": "Worüber? • Darüber",
        "level": "A2",
        "grammar_notes": "Directed at a circumstance: 'über + Akkusativ'.",
        "adj_rank": 6,
    },
    {
        "adj_group": "wütend",
        "adjective": "wütend",
        "prep": "auf",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "furious at / enraged with (a PERSON)",
        "sentence_de": "Sie ist furchtbar wütend {PREP} ihren unzuverlässigen Nachbarn.",
        "sentence_en": "She is terribly furious at her unreliable neighbor.",
        "question_structure": "Auf wen?",
        "level": "A2",
        "grammar_notes": "Furious at an individual: 'auf + Akkusativ'.",
        "adj_rank": 7,
    },
    {
        "adj_group": "wütend",
        "adjective": "wütend",
        "prep": "über",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "furious about (a MATTER or situation)",
        "sentence_de": "Die Bürger sind wütend {PREP} die erneute Erhöhung der Ticketpreise.",
        "sentence_en": "Citizens are furious about the renewed increase in ticket prices.",
        "question_structure": "Worüber? • Darüber",
        "level": "A2",
        "grammar_notes": "Furious about an issue/event: 'über + Akkusativ'.",
        "adj_rank": 7,
    },
    {
        "adj_group": "froh",
        "adjective": "froh",
        "prep": "über",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "glad about / happy about",
        "sentence_de": "Wir sind alle sehr froh {PREP} die erfreulichen Nachrichten.",
        "sentence_en": "We are all very glad about the pleasing news.",
        "question_structure": "Worüber? • Darüber",
        "level": "A1",
        "grammar_notes": "Always takes 'über + Akkusativ'.",
        "adj_rank": 8,
    },
    {
        "adj_group": "glücklich",
        "adjective": "glücklich",
        "prep": "über",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "happy about / delighted with",
        "sentence_de": "Sie ist überglücklich {PREP} das bestandene Vorstellungsgespräch.",
        "sentence_en": "She is overjoyed about the passed job interview.",
        "question_structure": "Worüber? • Darüber",
        "level": "A1",
        "grammar_notes": "Takes 'über + Akkusativ'.",
        "adj_rank": 9,
    },
    {
        "adj_group": "traurig",
        "adjective": "traurig",
        "prep": "über",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "sad about",
        "sentence_de": "Das Kind war untröstlich und traurig {PREP} den Verlust des Spielzeugs.",
        "sentence_en": "The child was inconsolable and sad about the loss of the toy.",
        "question_structure": "Worüber? • Darüber",
        "level": "A1",
        "grammar_notes": "Always 'über + Akkusativ'.",
        "adj_rank": 10,
    },
    {
        "adj_group": "fertig",
        "adjective": "fertig",
        "prep": "mit",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "finished with / done with",
        "sentence_de": "Bist du schon fertig {PREP} deinen Hausaufgaben?",
        "sentence_en": "Are you already finished with your homework?",
        "question_structure": "Womit? • Damit / Mit wem?",
        "level": "A1",
        "grammar_notes": "Completion of a task or parting with someone ('Ich bin fertig mit ihm').",
        "adj_rank": 11,
    },
    {
        "adj_group": "verliebt",
        "adjective": "verliebt",
        "prep": "in",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "in love with",
        "sentence_de": "Romeo war unsterblich {PREP} Julia verliebt.",
        "sentence_en": "Romeo was hopelessly in love with Juliet.",
        "question_structure": "In wen?",
        "level": "A1",
        "grammar_notes": "Always takes 'in + Akkusativ'. Never 'mit'!",
        "adj_rank": 12,
    },
    {
        "adj_group": "verheiratet",
        "adjective": "verheiratet",
        "prep": "mit",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "married to",
        "sentence_de": "Mein Onkel ist seit über dreißig Jahren {PREP} einer Ärztin verheiratet.",
        "sentence_en": "My uncle has been married to a doctor for over thirty years.",
        "question_structure": "Mit wem?",
        "level": "A1",
        "grammar_notes": "Always takes 'mit + Dativ' (in German you are married 'with' someone).",
        "adj_rank": 13,
    },
    {
        "adj_group": "befreundet",
        "adjective": "befreundet",
        "prep": "mit",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "friends with",
        "sentence_de": "Sie ist seit der Schulzeit eng {PREP} meiner Schwester befreundet.",
        "sentence_en": "She has been close friends with my sister since school days.",
        "question_structure": "Mit wem?",
        "level": "A2",
        "grammar_notes": "Always takes 'mit + Dativ'.",
        "adj_rank": 14,
    },
    {
        "adj_group": "verwandt",
        "adjective": "verwandt",
        "prep": "mit",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "related to",
        "sentence_de": "Ist er eigentlich über drei Ecken {PREP} dir verwandt?",
        "sentence_en": "Is he actually distantly related to you?",
        "question_structure": "Mit wem?",
        "level": "A2",
        "grammar_notes": "Biological or familial relationship: 'mit + Dativ'.",
        "adj_rank": 15,
    },

    # ==========================================
    # TIER 2: Essential Intermediate (A2 - B1)
    # ==========================================
    {
        "adj_group": "abhängig",
        "adjective": "abhängig",
        "prep": "von",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "dependent on",
        "sentence_de": "Unsere Pläne sind völlig abhängig {PREP} der aktuellen Wetterlage.",
        "sentence_en": "Our plans are completely dependent on the current weather situation.",
        "question_structure": "Wovon? • Davon / Von wem?",
        "level": "A2",
        "grammar_notes": "Derived from 'abhängen von + Dat'.",
        "adj_rank": 16,
    },
    {
        "adj_group": "abhängig",
        "adjective": "unabhängig",
        "prep": "von",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "independent of / regardless of",
        "sentence_de": "Das Gesetz gilt für alle Bürger, ganz unabhängig {PREP} ihrem Einkommen.",
        "sentence_en": "The law applies to all citizens, quite independent of their income.",
        "question_structure": "Wovon? • Davon",
        "level": "B1",
        "grammar_notes": "Takes 'von + Dativ'. Frequently used as an adverb ('unabhängig davon').",
        "adj_rank": 16,
    },
    {
        "adj_group": "angewiesen",
        "adjective": "angewiesen",
        "prep": "auf",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "reliant on / dependent upon",
        "sentence_de": "In ländlichen Gebieten ist man {PREP} öffentliche Verkehrsmittel angewiesen.",
        "sentence_en": "In rural areas, one is reliant on public transport.",
        "question_structure": "Worauf? • Darauf / Auf wen?",
        "level": "B1",
        "grammar_notes": "Strong dependency/need. Always 'auf + Akkusativ'.",
        "adj_rank": 17,
    },
    {
        "adj_group": "bereit",
        "adjective": "bereit",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "ready for / willing to do (an action or compromise)",
        "sentence_de": "Beide Parteien waren erfreulicherweise {PREP} einem Kompromiss bereit.",
        "sentence_en": "Fortunately, both parties were ready for a compromise.",
        "question_structure": "Wozu? • Dazu",
        "level": "A2",
        "grammar_notes": "Willingness to take an action: 'zu + Dativ'.",
        "adj_rank": 18,
    },
    {
        "adj_group": "bereit",
        "adjective": "bereit",
        "prep": "für",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "ready for (an upcoming event, journey, or challenge)",
        "sentence_de": "Bist du schon startklar und bereit {PREP} die große Reise?",
        "sentence_en": "Are you already set and ready for the big journey?",
        "question_structure": "Wofür? • Dafür",
        "level": "A2",
        "grammar_notes": "Preparedness for an event: 'für + Akkusativ'.",
        "adj_rank": 18,
    },
    {
        "adj_group": "bekannt",
        "adjective": "bekannt",
        "prep": "für",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "known for / famous for (a quality, product, or feature)",
        "sentence_de": "München ist weltweit bekannt {PREP} das berühmte Oktoberfest.",
        "sentence_en": "Munich is known worldwide for the famous Oktoberfest.",
        "question_structure": "Wofür? • Dafür",
        "level": "A2",
        "grammar_notes": "Feature or hallmark: 'für + Akkusativ'.",
        "adj_rank": 19,
    },
    {
        "adj_group": "bekannt",
        "adjective": "bekannt",
        "prep": "bei",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "known among / well-known to (a group of people)",
        "sentence_de": "Der junge Autor ist vor allem {PREP} jugendlichen Lesern bekannt.",
        "sentence_en": "The young author is particularly well-known among teenage readers.",
        "question_structure": "Bei wem?",
        "level": "B1",
        "grammar_notes": "Audience or circle of familiarity: 'bei + Dativ'.",
        "adj_rank": 19,
    },
    {
        "adj_group": "beliebt",
        "adjective": "beliebt",
        "prep": "bei",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "popular with / liked by",
        "sentence_de": "Die freundliche Lehrerin ist überaus beliebt {PREP} ihren Schülern.",
        "sentence_en": "The friendly teacher is extremely popular with her students.",
        "question_structure": "Bei wem?",
        "level": "A2",
        "grammar_notes": "The demographic or group takes 'bei + Dativ'.",
        "adj_rank": 20,
    },
    {
        "adj_group": "begeistert",
        "adjective": "begeistert",
        "prep": "von",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "enthusiastic about / thrilled by",
        "sentence_de": "Das Publikum war restlos begeistert {PREP} der grandiosen Aufführung.",
        "sentence_en": "The audience was utterly thrilled by the magnificent performance.",
        "question_structure": "Wovon? • Davon / Von wem?",
        "level": "A2",
        "grammar_notes": "Takes 'von + Dativ'. Expresses immense admiration.",
        "adj_rank": 21,
    },
    {
        "adj_group": "berühmt",
        "adjective": "berühmt",
        "prep": "für",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "famous for",
        "sentence_de": "Die Schweiz ist weltberühmt {PREP} ihre feine Schokolade und Uhren.",
        "sentence_en": "Switzerland is world-famous for its fine chocolate and watches.",
        "question_structure": "Wofür? • Dafür",
        "level": "A2",
        "grammar_notes": "Synonym to 'bekannt für + Akk'.",
        "adj_rank": 22,
    },
    {
        "adj_group": "beschäftigt",
        "adjective": "beschäftigt",
        "prep": "mit",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "busy with / occupied with",
        "sentence_de": "Er ist momentan vollauf {PREP} den Vorbereitungen für die Messe beschäftigt.",
        "sentence_en": "He is currently fully occupied with preparations for the trade fair.",
        "question_structure": "Womit? • Damit",
        "level": "A2",
        "grammar_notes": "Derived from 'sich beschäftigen mit + Dat'.",
        "adj_rank": 23,
    },
    {
        "adj_group": "beteiligt",
        "adjective": "beteiligt",
        "prep": "an",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "involved in / participant in",
        "sentence_de": "Mehrere renommierte Firmen sind {PREP} dem Großprojekt beteiligt.",
        "sentence_en": "Several renowned companies are involved in the major project.",
        "question_structure": "Woran? • Daran / An wem?",
        "level": "B1",
        "grammar_notes": "Participation or partnership takes 'an + Dativ'.",
        "adj_rank": 24,
    },
    {
        "adj_group": "eifersüchtig",
        "adjective": "eifersüchtig",
        "prep": "auf",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "jealous of (in a relationship or affection)",
        "sentence_de": "Er ist grundlos eifersüchtig {PREP} jeden Mann, der sie anlächelt.",
        "sentence_en": "He is groundlessly jealous of every man who smiles at her.",
        "question_structure": "Auf wen? / Worauf?",
        "level": "B1",
        "grammar_notes": "Romantic or personal jealousy: 'auf + Akkusativ'.",
        "adj_rank": 25,
    },
    {
        "adj_group": "neidisch",
        "adjective": "neidisch",
        "prep": "auf",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "envious of (possessions, success, status)",
        "sentence_de": "Niemand sollte neidisch {PREP} den plötzlichen Erfolg anderer sein.",
        "sentence_en": "Nobody should be envious of other people's sudden success.",
        "question_structure": "Worauf? • Darauf / Auf wen?",
        "level": "B1",
        "grammar_notes": "Material or professional envy: 'auf + Akkusativ'.",
        "adj_rank": 26,
    },
    {
        "adj_group": "einverstanden",
        "adjective": "einverstanden",
        "prep": "mit",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "in agreement with / agreed to",
        "sentence_de": "Bist du {PREP} dieser vorgeschlagenen Regelung einverstanden?",
        "sentence_en": "Are you in agreement with this proposed regulation?",
        "question_structure": "Womit? • Damit",
        "level": "A2",
        "grammar_notes": "Formula: mit etwas (Dat) einverstanden sein.",
        "adj_rank": 27,
    },
    {
        "adj_group": "enttäuscht",
        "adjective": "enttäuscht",
        "prep": "von",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "disappointed in / by (a PERSON or their performance)",
        "sentence_de": "Der Trainer war zutiefst enttäuscht {PREP} der lustlosen Mannschaft.",
        "sentence_en": "The coach was deeply disappointed in the listless team.",
        "question_structure": "Von wem? / Wovon?",
        "level": "B1",
        "grammar_notes": "Disappointment in a person: 'von + Dativ'.",
        "adj_rank": 28,
    },
    {
        "adj_group": "enttäuscht",
        "adjective": "enttäuscht",
        "prep": "über",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "disappointed about (an EVENT, outcome, or fact)",
        "sentence_de": "Sie war bitter enttäuscht {PREP} das schlechte Prüfungsergebnis.",
        "sentence_en": "She was bitterly disappointed about the poor exam result.",
        "question_structure": "Worüber? • Darüber",
        "level": "B1",
        "grammar_notes": "Disappointment about a circumstance: 'über + Akkusativ'.",
        "adj_rank": 28,
    },
    {
        "adj_group": "entschlossen",
        "adjective": "entschlossen",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "determined to / resolved upon",
        "sentence_de": "Die Regierung ist fest {PREP} durchgreifenden Reformen entschlossen.",
        "sentence_en": "The government is firmly resolved upon radical reforms.",
        "question_structure": "Wozu? • Dazu",
        "level": "B1",
        "grammar_notes": "Takes 'zu + Dativ'. Firm resolution.",
        "adj_rank": 29,
    },
    {
        "adj_group": "erstaunt",
        "adjective": "erstaunt",
        "prep": "über",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "astonished at / amazed by",
        "sentence_de": "Wir waren sehr erstaunt {PREP} seine perfekten Deutschkenntnisse.",
        "sentence_en": "We were very astonished at his perfect German skills.",
        "question_structure": "Worüber? • Darüber",
        "level": "B1",
        "grammar_notes": "Takes 'über + Akkusativ'.",
        "adj_rank": 30,
    },
    {
        "adj_group": "fähig",
        "adjective": "fähig",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "capable of",
        "sentence_de": "In einer Krise ist der Mensch oft {PREP} ungeahnten Leistungen fähig.",
        "sentence_en": "In a crisis, a person is often capable of unexpected achievements.",
        "question_structure": "Wozu? • Dazu",
        "level": "B1",
        "grammar_notes": "Always takes 'zu + Dativ'.",
        "adj_rank": 31,
    },
    {
        "adj_group": "frei",
        "adjective": "frei",
        "prep": "von",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "free from / free of",
        "sentence_de": "Dieses Produkt ist garantiert frei {PREP} künstlichen Konservierungsstoffen.",
        "sentence_en": "This product is guaranteed free of artificial preservatives.",
        "question_structure": "Wovon? • Davon",
        "level": "B1",
        "grammar_notes": "Absence of unwanted substances or burdens.",
        "adj_rank": 32,
    },
    {
        "adj_group": "freundlich",
        "adjective": "freundlich",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "friendly to / kind towards",
        "sentence_de": "Das Hotelpersonal war immer überaus freundlich {PREP} allen Gästen.",
        "sentence_en": "The hotel staff was always extremely friendly to all guests.",
        "question_structure": "Zu wem?",
        "level": "A2",
        "grammar_notes": "Takes 'zu + Dativ' (less commonly: 'gegenüber + Dat').",
        "adj_rank": 33,
    },
    {
        "adj_group": "höflich",
        "adjective": "höflich",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "polite to / courteous towards",
        "sentence_de": "Ein Kellner sollte stets höflich {PREP} allen Kunden sein.",
        "sentence_en": "A waiter should always be polite to all customers.",
        "question_structure": "Zu wem?",
        "level": "A2",
        "grammar_notes": "Takes 'zu + Dativ'.",
        "adj_rank": 34,
    },
    {
        "adj_group": "streng",
        "adjective": "streng",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "strict with / stern towards",
        "sentence_de": "Manche Eltern sind übertrieben streng {PREP} ihren heranwachsenden Kindern.",
        "sentence_en": "Some parents are overly strict with their adolescent children.",
        "question_structure": "Zu wem?",
        "level": "B1",
        "grammar_notes": "Takes 'zu + Dativ'.",
        "adj_rank": 35,
    },
    {
        "adj_group": "geeignet",
        "adjective": "geeignet",
        "prep": "für",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "suitable for (a target group or purpose)",
        "sentence_de": "Diese Software ist besonders gut {PREP} kleine und mittlere Betriebe geeignet.",
        "sentence_en": "This software is particularly well suited for small and medium-sized businesses.",
        "question_structure": "Wofür? • Dafür / Für wen?",
        "level": "B1",
        "grammar_notes": "Takes 'für + Akkusativ'.",
        "adj_rank": 36,
    },
    {
        "adj_group": "gespannt",
        "adjective": "gespannt",
        "prep": "auf",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "eager to see / in suspense about / curious about (a future outcome)",
        "sentence_de": "Ich bin schon unheimlich gespannt {PREP} das morgige Endspiel!",
        "sentence_en": "I am already incredibly curious/eager about tomorrow's final game!",
        "question_structure": "Worauf? • Darauf",
        "level": "A2",
        "grammar_notes": "Anticipating a revelation or outcome. Always 'auf + Akkusativ'.",
        "adj_rank": 37,
    },
    {
        "adj_group": "gewöhnt",
        "adjective": "gewöhnt",
        "prep": "an",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "used to / accustomed to",
        "sentence_de": "Als Skandinavier ist er {PREP} eisige Winter gewöhnt.",
        "sentence_en": "As a Scandinavian, he is used to freezing winters.",
        "question_structure": "Woran? • Daran / An wen?",
        "level": "B1",
        "grammar_notes": "State of being accustomed: 'an + Akkusativ'.",
        "adj_rank": 38,
    },
    {
        "adj_group": "gut",
        "adjective": "gut",
        "prep": "in",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "good at (a subject, discipline, or sport)",
        "sentence_de": "Schon als Schüler war er außergewöhnlich gut {PREP} Mathematik.",
        "sentence_en": "Even as a pupil he was exceptionally good at mathematics.",
        "question_structure": "Worin? • Darin",
        "level": "A1",
        "grammar_notes": "Proficiency in a field takes 'in + Dativ'.",
        "adj_rank": 39,
    },
    {
        "adj_group": "gut",
        "adjective": "gut",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "kind to / good to (a person)",
        "sentence_de": "Er war während der schweren Zeit immer gut {PREP} mir.",
        "sentence_en": "He was always kind to me during the difficult time.",
        "question_structure": "Zu wem?",
        "level": "A2",
        "grammar_notes": "Interpersonal treatment: 'zu + Dativ'.",
        "adj_rank": 39,
    },
    {
        "adj_group": "schlecht",
        "adjective": "schlecht",
        "prep": "in",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "bad at / poor in (a subject or skill)",
        "sentence_de": "Leider bin ich ziemlich schlecht {PREP} Auswendiglernen von Jahreszahlen.",
        "sentence_en": "Unfortunately, I am rather bad at memorizing dates.",
        "question_structure": "Worin? • Darin",
        "level": "A2",
        "grammar_notes": "Opposite of 'gut in + Dat'.",
        "adj_rank": 40,
    },
    {
        "adj_group": "neugierig",
        "adjective": "neugierig",
        "prep": "auf",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "curious about",
        "sentence_de": "Die Kinder waren furchtbar neugierig {PREP} die eingepackten Geschenke.",
        "sentence_en": "The children were terribly curious about the wrapped gifts.",
        "question_structure": "Worauf? • Darauf / Auf wen?",
        "level": "A2",
        "grammar_notes": "Always takes 'auf + Akkusativ'.",
        "adj_rank": 41,
    },
    {
        "adj_group": "nützlich",
        "adjective": "nützlich",
        "prep": "für",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "useful for",
        "sentence_de": "Diese praktischen Tipps sind besonders nützlich {PREP} Sprachanfänger.",
        "sentence_en": "These practical tips are particularly useful for language beginners.",
        "question_structure": "Wofür? • Dafür / Für wen?",
        "level": "B1",
        "grammar_notes": "Utility takes 'für + Akkusativ'.",
        "adj_rank": 42,
    },
    {
        "adj_group": "offen",
        "adjective": "offen",
        "prep": "für",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "open to (new ideas, suggestions)",
        "sentence_de": "Unsere Abteilung ist jederzeit offen {PREP} innovative Vorschläge.",
        "sentence_en": "Our department is always open to innovative suggestions.",
        "question_structure": "Wofür? • Dafür",
        "level": "B1",
        "grammar_notes": "Receptivity to suggestions: 'für + Akkusativ'.",
        "adj_rank": 43,
    },
    {
        "adj_group": "reich",
        "adjective": "reich",
        "prep": "an",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "rich in (vitamins, nutrients, minerals)",
        "sentence_de": "Frische Beeren sind besonders reich {PREP} wertvollen Vitaminen.",
        "sentence_en": "Fresh berries are particularly rich in valuable vitamins.",
        "question_structure": "Woran? • Daran",
        "level": "B1",
        "grammar_notes": "Abundance of a resource takes 'an + Dativ'.",
        "adj_rank": 44,
    },
    {
        "adj_group": "arm",
        "adjective": "arm",
        "prep": "an",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "poor in / low in",
        "sentence_de": "Diese karge Wüstenregion ist extrem arm {PREP} Wasser und Vegetation.",
        "sentence_en": "This barren desert region is extremely poor in water and vegetation.",
        "question_structure": "Woran? • Daran",
        "level": "B1",
        "grammar_notes": "Opposite of 'reich an + Dat'.",
        "adj_rank": 45,
    },
    {
        "adj_group": "schädlich",
        "adjective": "schädlich",
        "prep": "für",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "harmful to / damaging to",
        "sentence_de": "Plastikmüll im Meer ist extrem schädlich {PREP} die Tierwelt.",
        "sentence_en": "Plastic waste in the ocean is extremely harmful to wildlife.",
        "question_structure": "Wofür? • Dafür",
        "level": "B1",
        "grammar_notes": "Takes 'für + Akkusativ'.",
        "adj_rank": 46,
    },
    {
        "adj_group": "schuld",
        "adjective": "schuld",
        "prep": "an",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "to blame for / at fault for",
        "sentence_de": "Niemand von uns ist schuld {PREP} diesem unglücklichen Unfall.",
        "sentence_en": "None of us is to blame for this unfortunate accident.",
        "question_structure": "Woran? • Daran / An wem?",
        "level": "A2",
        "grammar_notes": "Uninflected predicate adjective: 'schuld sein an + Dativ'.",
        "adj_rank": 47,
    },
    {
        "adj_group": "typisch",
        "adjective": "typisch",
        "prep": "für",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "typical of",
        "sentence_de": "Diese typische Gastfreundschaft ist bezeichnend {PREP} die Region.",
        "sentence_en": "This typical hospitality is characteristic of the region.",
        "question_structure": "Wofür? • Dafür",
        "level": "A2",
        "grammar_notes": "Always 'für + Akkusativ'.",
        "adj_rank": 48,
    },
    {
        "adj_group": "überzeugt",
        "adjective": "überzeugt",
        "prep": "von",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "convinced of",
        "sentence_de": "Ich bin felsenfest {PREP} der Richtigkeit dieser Maßnahme überzeugt.",
        "sentence_en": "I am rock-solidly convinced of the correctness of this measure.",
        "question_structure": "Wovon? • Davon / Von wem?",
        "level": "B1",
        "grammar_notes": "Derived from 'überzeugen von + Dat'.",
        "adj_rank": 49,
    },
    {
        "adj_group": "verantwortlich",
        "adjective": "verantwortlich",
        "prep": "für",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "responsible for",
        "sentence_de": "Wer ist in Ihrer Abteilung verantwortlich {PREP} die IT-Sicherheit?",
        "sentence_en": "Who in your department is responsible for IT security?",
        "question_structure": "Wofür? • Dafür / Für wen?",
        "level": "B1",
        "grammar_notes": "Duty or liability takes 'für + Akkusativ'.",
        "adj_rank": 50,
    },
    {
        "adj_group": "zuständig",
        "adjective": "zuständig",
        "prep": "für",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "in charge of / responsible for (an administrative duty)",
        "sentence_de": "Frau Müller ist {PREP} die Bearbeitung aller Visa-Anträge zuständig.",
        "sentence_en": "Ms. Müller is in charge of processing all visa applications.",
        "question_structure": "Wofür? • Dafür",
        "level": "B1",
        "grammar_notes": "Official or bureaucratic competence.",
        "adj_rank": 51,
    },
    {
        "adj_group": "verrückt",
        "adjective": "verrückt",
        "prep": "nach",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "crazy about / mad about",
        "sentence_de": "Die Kinder sind förmlich verrückt {PREP} italienischem Schokoladeneis.",
        "sentence_en": "The children are positively crazy about Italian chocolate ice cream.",
        "question_structure": "Wonach? • Danach / Nach wem?",
        "level": "A2",
        "grammar_notes": "Obsessive liking: 'nach + Dativ'.",
        "adj_rank": 52,
    },

    # ==========================================
    # TIER 3: Advanced & Nuanced (B1 - B2)
    # ==========================================
    {
        "adj_group": "besorgt",
        "adjective": "besorgt",
        "prep": "um",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "worried about (someone's safety, health, or welfare)",
        "sentence_de": "Die Mutter war sehr besorgt {PREP} die Gesundheit ihres kranken Sohnes.",
        "sentence_en": "The mother was very worried about the health of her sick son.",
        "question_structure": "Worum? • Darum / Um wen?",
        "level": "B1",
        "grammar_notes": "Worry about personal well-being or safety: 'um + Akkusativ'.",
        "adj_rank": 53,
    },
    {
        "adj_group": "besorgt",
        "adjective": "besorgt",
        "prep": "über",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "concerned about / perturbed by (a political/economic situation)",
        "sentence_de": "Die Ökonomen sind besorgt {PREP} die steigende Inflation.",
        "sentence_en": "The economists are concerned about rising inflation.",
        "question_structure": "Worüber? • Darüber",
        "level": "B1",
        "grammar_notes": "Concern regarding broader public issues: 'über + Akkusativ'.",
        "adj_rank": 53,
    },
    {
        "adj_group": "skeptisch",
        "adjective": "skeptisch",
        "prep": "gegenüber",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "skeptical towards / about",
        "sentence_de": "Die Anleger stehen dem neuen Finanzplan skeptisch {PREP}über.",
        "sentence_en": "Investors are skeptical towards the new financial plan.",
        "question_structure": "Worüber? / Gegenüber wem?",
        "level": "B2",
        "grammar_notes": "Postposition/preposition 'gegenüber' always takes Dativ.",
        "adj_rank": 54,
    },
    {
        "adj_group": "aufgeschlossen",
        "adjective": "aufgeschlossen",
        "prep": "gegenüber",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "open-minded towards / receptive to",
        "sentence_de": "Sie zeigt sich {PREP} fremden Kulturen stets sehr aufgeschlossen.",
        "sentence_en": "She always shows herself to be very open-minded towards foreign cultures.",
        "question_structure": "Gegenüber wem?",
        "level": "B2",
        "grammar_notes": "Attitude towards others/innovations: takes Dativ.",
        "adj_rank": 55,
    },
    {
        "adj_group": "misstrauisch",
        "adjective": "misstrauisch",
        "prep": "gegenüber",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "distrustful of / suspicious towards",
        "sentence_de": "Er war von Natur aus {PREP} Fremden sehr misstrauisch.",
        "sentence_en": "He was by nature very suspicious towards strangers.",
        "question_structure": "Gegenüber wem?",
        "level": "B2",
        "grammar_notes": "Always takes 'gegenüber + Dativ'.",
        "adj_rank": 56,
    },
    {
        "adj_group": "empfindlich",
        "adjective": "empfindlich",
        "prep": "gegen",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "sensitive to (cold, heat, light, criticism)",
        "sentence_de": "Meine Zähne sind extrem empfindlich {PREP} Kälte und Säure.",
        "sentence_en": "My teeth are extremely sensitive to cold and acid.",
        "question_structure": "Wogegen? • Dagegen",
        "level": "B1",
        "grammar_notes": "Physical or sensory sensitivity: 'gegen + Akkusativ'.",
        "adj_rank": 57,
    },
    {
        "adj_group": "immun",
        "adjective": "immun",
        "prep": "gegen",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "immune to (infection, criticism, charm)",
        "sentence_de": "Nach der Impfung ist der Organismus immun {PREP} den Erreger.",
        "sentence_en": "After the vaccination, the organism is immune to the pathogen.",
        "question_structure": "Wogegen? • Dagegen",
        "level": "B2",
        "grammar_notes": "Resistance takes 'gegen + Akkusativ'.",
        "adj_rank": 58,
    },
    {
        "adj_group": "allergisch",
        "adjective": "allergisch",
        "prep": "auf",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "allergic to (pollen, foods) / reacting badly to",
        "sentence_de": "Sie reagiert stark allergisch {PREP} Katzenhaare.",
        "sentence_en": "She reacts severely allergic to cat hair.",
        "question_structure": "Worauf? • Darauf",
        "level": "A2",
        "grammar_notes": "Takes 'auf + Akkusativ'. (Informally also 'gegen + Akk').",
        "adj_rank": 59,
    },
    {
        "adj_group": "überrascht",
        "adjective": "überrascht",
        "prep": "über",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "surprised at / by (an outcome or fact)",
        "sentence_de": "Alle waren positiv überrascht {PREP} die schnelle Genesung.",
        "sentence_en": "Everyone was pleasantly surprised at the swift recovery.",
        "question_structure": "Worüber? • Darüber",
        "level": "A2",
        "grammar_notes": "Reaction to an event: 'über + Akkusativ'.",
        "adj_rank": 60,
    },
    {
        "adj_group": "überrascht",
        "adjective": "überrascht",
        "prep": "von",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "caught off-guard by / surprised by (a person or unforeseen act)",
        "sentence_de": "Der Torwart wurde völlig {PREP} dem weiten Schuss überrascht.",
        "sentence_en": "The goalkeeper was completely surprised by the long shot.",
        "question_structure": "Wovon? • Davon",
        "level": "B1",
        "grammar_notes": "Agent or passive cause: 'von + Dativ'.",
        "adj_rank": 60,
    },
    {
        "adj_group": "voll",
        "adjective": "voll",
        "prep": "von",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "full of / covered in",
        "sentence_de": "Nach dem Waldspaziergang waren seine Schuhe voll {PREP} Schlamm.",
        "sentence_en": "After the forest walk, his shoes were full of mud.",
        "question_structure": "Wovon? • Davon",
        "level": "A2",
        "grammar_notes": "Can also be used with plain Genitive ('voller Freude').",
        "adj_rank": 61,
    },
    {
        "adj_group": "rot",
        "adjective": "rot",
        "prep": "vor",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "red with (anger, embarrassment, shame)",
        "sentence_de": "Aus lauter Verlegenheit wurde der Junge knallrot {PREP} Scham.",
        "sentence_en": "Out of sheer embarrassment, the boy turned bright red with shame.",
        "question_structure": "Wovor? • Davor",
        "level": "B1",
        "grammar_notes": "Emotional involuntary physical reactions take 'vor + Dativ'.",
        "adj_rank": 62,
    },
    {
        "adj_group": "stumm",
        "adjective": "stumm",
        "prep": "vor",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "mute / speechless with (shock, astonishment)",
        "sentence_de": "Die Zeugen blieben stumm {PREP} Entsetzen über den Vorfall.",
        "sentence_en": "The witnesses remained mute with horror at the incident.",
        "question_structure": "Wovor? • Davor",
        "level": "B2",
        "grammar_notes": "Emotional paralysis takes 'vor + Dativ'.",
        "adj_rank": 63,
    },
    {
        "adj_group": "blass",
        "adjective": "blass",
        "prep": "vor",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "pale with (fear, shock, envy)",
        "sentence_de": "Er wurde kreidebleich und blass {PREP} Schreck über den Unfall.",
        "sentence_en": "He turned chalk-white and pale with shock over the accident.",
        "question_structure": "Wovor? • Davor",
        "level": "B1",
        "grammar_notes": "Takes 'vor + Dativ' (e.g. blass vor Neid).",
        "adj_rank": 64,
    },
    {
        "adj_group": "blind",
        "adjective": "blind",
        "prep": "auf",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "blind in (an eye - anatomical)",
        "sentence_de": "Der alte Kater ist leider {PREP} dem linken Auge völlig blind.",
        "sentence_en": "The old tomcat is unfortunately completely blind in the left eye.",
        "question_structure": "Worauf?",
        "level": "B1",
        "grammar_notes": "Physical blindness in one eye: 'auf + Dativ'.",
        "adj_rank": 65,
    },
    {
        "adj_group": "blind",
        "adjective": "blind",
        "prep": "für",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "blind to (faults, dangers, risks - figurative)",
        "sentence_de": "Vor lauter Liebe war er blind {PREP} ihre vielen Fehler.",
        "sentence_en": "Out of sheer love, he was blind to her many flaws.",
        "question_structure": "Wofür? • Dafür",
        "level": "B2",
        "grammar_notes": "Figurative blindness/ignorance: 'für + Akkusativ'.",
        "adj_rank": 65,
    },
    {
        "adj_group": "taub",
        "adjective": "taub",
        "prep": "auf",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "deaf in (an ear - anatomical)",
        "sentence_de": "Seit der Explosion ist der Soldat {PREP} dem rechten Ohr taub.",
        "sentence_en": "Since the explosion, the soldier has been deaf in his right ear.",
        "question_structure": "Worauf?",
        "level": "B1",
        "grammar_notes": "Physical deafness in an ear: 'auf + Dativ'.",
        "adj_rank": 66,
    },
    {
        "adj_group": "taub",
        "adjective": "taub",
        "prep": "für",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "deaf to (arguments, advice - figurative)",
        "sentence_de": "Der Diktator blieb taub {PREP} alle friedlichen Bitten des Volkes.",
        "sentence_en": "The dictator remained deaf to all peaceful pleas of the people.",
        "question_structure": "Wofür? • Dafür",
        "level": "B2",
        "grammar_notes": "Refusing to heed reasoning: 'für + Akkusativ'.",
        "adj_rank": 66,
    },
    {
        "adj_group": "verbittert",
        "adjective": "verbittert",
        "prep": "über",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "bitter about (injustice, life circumstances)",
        "sentence_de": "Er war tief verbittert {PREP} die ungerechtfertigte Kündigung.",
        "sentence_en": "He was deeply bitter about the unjustified dismissal.",
        "question_structure": "Worüber? • Darüber",
        "level": "B2",
        "grammar_notes": "Resentment takes 'über + Akkusativ'.",
        "adj_rank": 67,
    },
    {
        "adj_group": "verärgert",
        "adjective": "verärgert",
        "prep": "über",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "exasperated / annoyed about",
        "sentence_de": "Die Passagiere waren extrem verärgert {PREP} die stundenlange Verspätung.",
        "sentence_en": "The passengers were extremely annoyed about the hours-long delay.",
        "question_structure": "Worüber? • Darüber",
        "level": "B1",
        "grammar_notes": "Takes 'über + Akkusativ'.",
        "adj_rank": 68,
    },
    {
        "adj_group": "aufmerksam",
        "adjective": "aufmerksam",
        "prep": "auf",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "attentive to / aware of / alerted to",
        "sentence_de": "Die Polizei wurde durch einen anonymen Hinweis {PREP} das Versteck aufmerksam.",
        "sentence_en": "The police became aware of the hideout through an anonymous tip.",
        "question_structure": "Worauf? • Darauf",
        "level": "B1",
        "grammar_notes": "Formula: aufmerksam werden/machen auf + Akk.",
        "adj_rank": 69,
    },
    {
        "adj_group": "hungrig",
        "adjective": "hungrig",
        "prep": "nach",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "hungry for / craving (success, news, power)",
        "sentence_de": "Die junge Athletin ist hungrig {PREP} neuen Rekorden und Siegen.",
        "sentence_en": "The young athlete is hungry for new records and victories.",
        "question_structure": "Wonach? • Danach",
        "level": "B2",
        "grammar_notes": "Figurative hunger/craving takes 'nach + Dativ'.",
        "adj_rank": 70,
    },
    {
        "adj_group": "durstig",
        "adjective": "durstig",
        "prep": "nach",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "thirsty for (knowledge, justice, revenge)",
        "sentence_de": "Wissenschaftler sind stets durstig {PREP} neuen Erkenntnissen.",
        "sentence_en": "Scientists are always thirsty for new insights.",
        "question_structure": "Wonach? • Danach",
        "level": "B2",
        "grammar_notes": "Takes 'nach + Dativ'.",
        "adj_rank": 71,
    },
    {
        "adj_group": "süchtig",
        "adjective": "süchtig",
        "prep": "nach",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "addicted to",
        "sentence_de": "Immer mehr Jugendliche sind süchtig {PREP} sozialen Medien.",
        "sentence_en": "More and more teenagers are addicted to social media.",
        "question_structure": "Wonach? • Danach",
        "level": "B1",
        "grammar_notes": "Addiction takes 'nach + Dativ'.",
        "adj_rank": 72,
    },
    {
        "adj_group": "besessen",
        "adjective": "besessen",
        "prep": "von",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "obsessed with (an idea, mission, perfection)",
        "sentence_de": "Der Erfinder war förmlich besessen {PREP} seiner neuen Vision.",
        "sentence_en": "The inventor was positively obsessed with his new vision.",
        "question_structure": "Wovon? • Davon / Von wem?",
        "level": "B2",
        "grammar_notes": "Obsession takes 'von + Dativ'.",
        "adj_rank": 73,
    },
    {
        "adj_group": "erfreut",
        "adjective": "erfreut",
        "prep": "über",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "pleased about / delighted with",
        "sentence_de": "Wir waren außerordentlich erfreut {PREP} deinen überraschenden Besuch.",
        "sentence_en": "We were extraordinarily pleased about your surprise visit.",
        "question_structure": "Worüber? • Darüber",
        "level": "B1",
        "grammar_notes": "Formal synonym for 'froh über + Akk'.",
        "adj_rank": 74,
    },
    {
        "adj_group": "beunruhigt",
        "adjective": "beunruhigt",
        "prep": "über",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "perturbed about / alarmed at",
        "sentence_de": "Die Bürger sind zutiefst beunruhigt {PREP} die zunehmende Kriminalität.",
        "sentence_en": "Citizens are deeply perturbed about the increasing crime.",
        "question_structure": "Worüber? • Darüber",
        "level": "B2",
        "grammar_notes": "Takes 'über + Akkusativ'.",
        "adj_rank": 75,
    },
    {
        "adj_group": "charakteristisch",
        "adjective": "charakteristisch",
        "prep": "für",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "characteristic of",
        "sentence_de": "Die spitzen Türme sind absolut charakteristisch {PREP} diese gotische Kathedrale.",
        "sentence_en": "The pointed towers are absolutely characteristic of this Gothic cathedral.",
        "question_structure": "Wofür? • Dafür",
        "level": "B2",
        "grammar_notes": "Distinctive feature: 'für + Akkusativ'.",
        "adj_rank": 76,
    },
    {
        "adj_group": "entscheidend",
        "adjective": "entscheidend",
        "prep": "für",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "decisive for / crucial to",
        "sentence_de": "Gute Teamarbeit ist oft entscheidend {PREP} den Projekterfolg.",
        "sentence_en": "Good teamwork is often decisive for project success.",
        "question_structure": "Wofür? • Dafür",
        "level": "B1",
        "grammar_notes": "Takes 'für + Akkusativ'.",
        "adj_rank": 77,
    },
    {
        "adj_group": "gefasst",
        "adjective": "gefasst",
        "prep": "auf",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "braced for / prepared for (unpleasant news or hardship)",
        "sentence_de": "Man muss im Leben {PREP} alle bösen Überraschungen gefasst sein.",
        "sentence_en": "One must be braced for all bad surprises in life.",
        "question_structure": "Worauf? • Darauf",
        "level": "B2",
        "grammar_notes": "Formula: gefasst sein auf + Akk (prepared for negative eventualities).",
        "adj_rank": 78,
    },
    {
        "adj_group": "nett",
        "adjective": "nett",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "kind to / nice to (a person)",
        "sentence_de": "Sei bitte immer nett {PREP} deinen jüngeren Geschwistern!",
        "sentence_en": "Please always be nice to your younger siblings!",
        "question_structure": "Zu wem?",
        "level": "A1",
        "grammar_notes": "Formula: nett sein zu + Dativ.",
        "adj_rank": 79,
    },
    {
        "adj_group": "beeindruckt",
        "adjective": "beeindruckt",
        "prep": "von",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "impressed by",
        "sentence_de": "Die Prüfungskommission war sichtlich beeindruckt {PREP} ihrem fundierten Fachwissen.",
        "sentence_en": "The examination board was visibly impressed by her sound specialist knowledge.",
        "question_structure": "Wovon? • Davon / Von wem?",
        "level": "A2",
        "grammar_notes": "Takes 'von + Dativ'. Very high frequency.",
        "adj_rank": 80,
    },
    {
        "adj_group": "fasziniert",
        "adjective": "fasziniert",
        "prep": "von",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "fascinated by",
        "sentence_de": "Die Kinder waren völlig fasziniert {PREP} den bunten Fischen im Aquarium.",
        "sentence_en": "The children were completely fascinated by the colorful fish in the aquarium.",
        "question_structure": "Wovon? • Davon / Von wem?",
        "level": "B1",
        "grammar_notes": "Takes 'von + Dativ'.",
        "adj_rank": 81,
    },
    {
        "adj_group": "erfahren",
        "adjective": "erfahren",
        "prep": "in",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "experienced in / skilled at",
        "sentence_de": "Sie ist außerordentlich erfahren {PREP} der Leitung internationaler Projekte.",
        "sentence_en": "She is extraordinarily experienced in managing international projects.",
        "question_structure": "Worin? • Darin",
        "level": "B1",
        "grammar_notes": "Professional competence takes 'in + Dativ'.",
        "adj_rank": 82,
    },
    {
        "adj_group": "sicher",
        "adjective": "sicher",
        "prep": "vor",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "safe from (danger, persecution, bad weather)",
        "sentence_de": "In der gemütlichen Berghütte waren die Wanderer sicher {PREP} dem Unwetter.",
        "sentence_en": "In the cozy mountain hut, the hikers were safe from the storm.",
        "question_structure": "Wovor? • Davor",
        "level": "A2",
        "grammar_notes": "Protection from harm takes 'vor + Dativ'.",
        "adj_rank": 83,
    },
    {
        "adj_group": "geschützt",
        "adjective": "geschützt",
        "prep": "vor",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "protected from / shielded against",
        "sentence_de": "Die sensible Elektronik ist gut {PREP} Feuchtigkeit und Staub geschützt.",
        "sentence_en": "The sensitive electronics are well protected from moisture and dust.",
        "question_structure": "Wovor? • Davor",
        "level": "B1",
        "grammar_notes": "Takes 'vor + Dativ'.",
        "adj_rank": 84,
    },
    {
        "adj_group": "getrennt",
        "adjective": "getrennt",
        "prep": "von",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "separated from",
        "sentence_de": "Seit zwei Jahren lebt er getrennt {PREP} seiner Ehefrau.",
        "sentence_en": "He has been living separated from his wife for two years.",
        "question_structure": "Von wem? / Wovon?",
        "level": "A2",
        "grammar_notes": "Physical or marital separation takes 'von + Dativ'.",
        "adj_rank": 85,
    },
    {
        "adj_group": "gleichgültig",
        "adjective": "gleichgültig",
        "prep": "gegenüber",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "indifferent towards / unconcerned about",
        "sentence_de": "Man darf dem Leid anderer Menschen niemals {PREP} gleichgültig sein.",
        "sentence_en": "One must never be indifferent towards the suffering of other people.",
        "question_structure": "Gegenüber wem? / Worüber?",
        "level": "B2",
        "grammar_notes": "Takes 'gegenüber + Dativ'. Can appear before or after the dative noun.",
        "adj_rank": 86,
    },
    {
        "adj_group": "machtlos",
        "adjective": "machtlos",
        "prep": "gegen",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "powerless against",
        "sentence_de": "Gegenüber extremen Naturgewalten ist der Mensch oft völlig machtlos {PREP} die Zerstörung.",
        "sentence_en": "Against extreme forces of nature, man is often completely powerless against destruction.",
        "question_structure": "Wogegen? • Dagegen",
        "level": "B1",
        "grammar_notes": "Takes 'gegen + Akkusativ'.",
        "adj_rank": 87,
    },
    {
        "adj_group": "entsetzt",
        "adjective": "entsetzt",
        "prep": "über",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "horrified at / appalled at",
        "sentence_de": "Die ganze Welt war entsetzt {PREP} das verheerende Erdbeben.",
        "sentence_en": "The whole world was horrified at the devastating earthquake.",
        "question_structure": "Worüber? • Darüber",
        "level": "B2",
        "grammar_notes": "Extreme shock takes 'über + Akkusativ'.",
        "adj_rank": 88,
    },
    {
        "adj_group": "empört",
        "adjective": "empört",
        "prep": "über",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "indignant at / outraged about",
        "sentence_de": "Die Belegschaft war empört {PREP} die plötzliche Schließung des Werks.",
        "sentence_en": "The workforce was outraged about the sudden closure of the plant.",
        "question_structure": "Worüber? • Darüber",
        "level": "B2",
        "grammar_notes": "Moral indignation takes 'über + Akkusativ'.",
        "adj_rank": 89,
    },
    {
        "adj_group": "sehnsüchtig",
        "adjective": "sehnsüchtig",
        "prep": "nach",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "longing for / yearning for",
        "sentence_de": "Der Exilant sehnte sich und blickte sehnsüchtig {PREP} seiner fernen Heimat.",
        "sentence_en": "The exile looked with yearning toward his distant homeland.",
        "question_structure": "Wonach? • Danach",
        "level": "B2",
        "grammar_notes": "Emotional longing takes 'nach + Dativ'.",
        "adj_rank": 90,
    },
]
