"""
Curated database of the most frequent German Noun-Verb Idioms (Nomen-Verb-Verbindungen).
Organized by frequency and CEFR level (B1 to C1).

Every entry includes:
- idiom_group: Base verb or theme
- idiom: Full fixed expression (e.g. 'in Frage kommen')
- phrase_cloze: Prepositional phrase to be blanked out (e.g. 'in Frage')
- prep: The core preposition (e.g. 'in')
- case: Prepositional case (+ Dat., + Akk.)
- case_type: 'dat', 'akk'
- simple_verb: The standard single-verb synonym (e.g. 'möglich sein')
- meaning_en: English translation
- sentence_de: Example sentence with {PHRASE} placeholder
- sentence_en: English translation of sentence
- level: CEFR level (B1, B2, C1)
- grammar_notes: Register, active/passive nuances, usage
- idiom_rank: Relative frequency rank
"""

RAW_IDIOM_DATA = [
    # ==========================================
    # TIER 1: Foundational Noun-Verb Idioms (B1 - B2)
    # ==========================================
    {
        "idiom_group": "kommen",
        "idiom": "in Frage kommen",
        "phrase_cloze": "in Frage",
        "prep": "in",
        "case": "+ Akk.",
        "case_type": "akk",
        "simple_verb": "möglich sein / denkbar sein",
        "meaning_en": "to be possible / to be considered / to be an option",
        "sentence_de": "Ein weiterer Aufschub des Projekts kommt für uns keinesfalls {PHRASE}.",
        "sentence_en": "A further postponement of the project is out of the question for us.",
        "level": "B1",
        "grammar_notes": "Very common in negative: 'nicht in Frage kommen' = out of the question.",
        "idiom_rank": 1,
    },
    {
        "idiom_group": "stehen",
        "idiom": "zur Verfügung stehen",
        "phrase_cloze": "zur Verfügung",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "simple_verb": "vorhanden sein / verfügbar sein",
        "meaning_en": "to be available / to be at someone's disposal (PASSIVE)",
        "sentence_de": "Für Fragen und Beratungen stehe ich Ihnen jederzeit gerne {PHRASE}.",
        "sentence_en": "I am gladly at your disposal at any time for questions and consultations.",
        "level": "B1",
        "grammar_notes": "Passive state. Contrast with the active 'zur Verfügung stellen'!",
        "idiom_rank": 2,
    },
    {
        "idiom_group": "stellen",
        "idiom": "zur Verfügung stellen",
        "phrase_cloze": "zur Verfügung",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "simple_verb": "bereitstellen / anbieten",
        "meaning_en": "to make available / to provide / to supply (ACTIVE)",
        "sentence_de": "Die Universität stellt den Forschern modernste Labore {PHRASE}.",
        "sentence_en": "The university makes state-of-the-art laboratories available to the researchers.",
        "level": "B1",
        "grammar_notes": "Active provision. Contrast with 'zur Verfügung stehen'!",
        "idiom_rank": 2,
    },
    {
        "idiom_group": "ziehen",
        "idiom": "in Betracht ziehen",
        "phrase_cloze": "in Betracht",
        "prep": "in",
        "case": "+ Akk.",
        "case_type": "akk",
        "simple_verb": "überlegen / abwägen / berücksichtigen",
        "meaning_en": "to take into consideration / to contemplate",
        "sentence_de": "Wir müssen alle denkbaren Risiken sorgfältig {PHRASE} ziehen.",
        "sentence_en": "We must carefully take all conceivable risks into consideration.",
        "level": "B1",
        "grammar_notes": "Active decision making: jemanden/etwas in Betracht ziehen.",
        "idiom_rank": 3,
    },
    {
        "idiom_group": "kommen",
        "idiom": "in Betracht kommen",
        "phrase_cloze": "in Betracht",
        "prep": "in",
        "case": "+ Akk.",
        "case_type": "akk",
        "simple_verb": "möglich sein / in Frage kommen",
        "meaning_en": "to come into consideration / to be eligible",
        "sentence_de": "Für diesen anspruchsvollen Posten kommen nur wenige Kandidaten {PHRASE}.",
        "sentence_en": "Only a few candidates come into consideration for this demanding post.",
        "level": "B2",
        "grammar_notes": "Passive potentiality: eligible or considered for a role.",
        "idiom_rank": 3,
    },
    {
        "idiom_group": "stellen",
        "idiom": "unter Beweis stellen",
        "phrase_cloze": "unter Beweis",
        "prep": "unter",
        "case": "+ Akk.",
        "case_type": "akk",
        "simple_verb": "beweisen",
        "meaning_en": "to prove / to demonstrate (skills, courage)",
        "sentence_de": "Im entscheidenden Spiel stellte sie ihre herausragende Klasse {PHRASE}.",
        "sentence_en": "In the decisive match, she proved her outstanding class.",
        "level": "B2",
        "grammar_notes": "Formula: sein Können / Mut unter Beweis stellen.",
        "idiom_rank": 4,
    },
    {
        "idiom_group": "nehmen",
        "idiom": "Abschied nehmen von",
        "phrase_cloze": "Abschied nehmen",
        "prep": "von",
        "case": "+ Dat.",
        "case_type": "dat",
        "simple_verb": "sich verabschieden",
        "meaning_en": "to say goodbye to / to bid farewell to",
        "sentence_de": "Vor der langen Auslandsreise mussten wir schweren Herzens {PHRASE} von unseren Freunden.",
        "sentence_en": "Before the long trip abroad, we had to bid farewell to our friends with a heavy heart.",
        "level": "B1",
        "grammar_notes": "Elevated expression for 'sich verabschieden von + Dat'.",
        "idiom_rank": 5,
    },
    {
        "idiom_group": "treten",
        "idiom": "in Kraft treten",
        "phrase_cloze": "in Kraft",
        "prep": "in",
        "case": "+ Akk.",
        "case_type": "akk",
        "simple_verb": "gültig werden",
        "meaning_en": "to take effect / to come into force (laws, regulations)",
        "sentence_de": "Die neue europäische Datenschutzverordnung tritt ab Januar {PHRASE}.",
        "sentence_en": "The new European data protection regulation takes effect from January.",
        "level": "B2",
        "grammar_notes": "Standard legal/journalistic term for legislation taking effect.",
        "idiom_rank": 6,
    },
    {
        "idiom_group": "setzen",
        "idiom": "außer Kraft setzen",
        "phrase_cloze": "außer Kraft",
        "prep": "außer",
        "case": "+ Dat.",
        "case_type": "dat",
        "simple_verb": "aufheben / annullieren",
        "meaning_en": "to repeal / to invalidate / to suspend",
        "sentence_de": "Das Verfassungsgericht setzte das umstrittene Gesetz mit sofortiger Wirkung {PHRASE}.",
        "sentence_en": "The Constitutional Court repealed the controversial law with immediate effect.",
        "level": "B2",
        "grammar_notes": "Opposite of 'in Kraft treten/setzen'.",
        "idiom_rank": 6,
    },
    {
        "idiom_group": "bringen",
        "idiom": "zur Sprache bringen",
        "phrase_cloze": "zur Sprache",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "simple_verb": "ansprechen / thematisieren",
        "meaning_en": "to bring up for discussion / to raise a topic (ACTIVE)",
        "sentence_de": "Der Betriebsrat wollte die schlechte Bezahlung in der Sitzung {PHRASE} bringen.",
        "sentence_en": "The works council wanted to bring up poor pay for discussion in the meeting.",
        "level": "B2",
        "grammar_notes": "Active raising of a subject. Contrast with 'zur Sprache kommen'!",
        "idiom_rank": 7,
    },
    {
        "idiom_group": "kommen",
        "idiom": "zur Sprache kommen",
        "phrase_cloze": "zur Sprache",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "simple_verb": "besprochen werden",
        "meaning_en": "to come up for discussion / to be discussed (PASSIVE)",
        "sentence_de": "In der heutigen Kabinettssitzung kam auch die Bildungsreform {PHRASE}.",
        "sentence_en": "In today's cabinet meeting, education reform also came up for discussion.",
        "level": "B2",
        "grammar_notes": "Passive occurrence of a topic in conversation.",
        "idiom_rank": 7,
    },
    {
        "idiom_group": "kommen",
        "idiom": "ums Leben kommen",
        "phrase_cloze": "ums Leben",
        "prep": "um",
        "case": "+ Akk.",
        "case_type": "akk",
        "simple_verb": "sterben (durch Unfall/Gewalt)",
        "meaning_en": "to lose one's life / to be killed (in an accident or catastrophe)",
        "sentence_de": "Bei dem schweren Autounfall auf der Autobahn kamen zwei Insassen {PHRASE}.",
        "sentence_en": "In the severe car crash on the highway, two occupants lost their lives.",
        "level": "B1",
        "grammar_notes": "High frequency in news reporting for accidental or unnatural deaths.",
        "idiom_rank": 8,
    },
    {
        "idiom_group": "nehmen",
        "idiom": "in Kauf nehmen",
        "phrase_cloze": "in Kauf",
        "prep": "in",
        "case": "+ Akk.",
        "case_type": "akk",
        "simple_verb": "akzeptieren / hinnehmen",
        "meaning_en": "to accept / to put up with (negative side-effects or risks)",
        "sentence_de": "Wer schnell reisen will, muss gelegentliche Verspätungen {PHRASE} nehmen.",
        "sentence_en": "Whoever wants to travel fast must put up with occasional delays.",
        "level": "B2",
        "grammar_notes": "Willingly accepting an unavoidable disadvantage.",
        "idiom_rank": 9,
    },
    {
        "idiom_group": "bringen",
        "idiom": "zu Ende bringen",
        "phrase_cloze": "zu Ende",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "simple_verb": "beenden / abschließen",
        "meaning_en": "to bring to an end / to finish (ACTIVE)",
        "sentence_de": "Trotz aller Widrigkeiten brachten die Bauherren das Projekt erfolgreich {PHRASE}.",
        "sentence_en": "Despite all adversities, the builders successfully brought the project to completion.",
        "level": "A2",
        "grammar_notes": "Actively concluding a task or project.",
        "idiom_rank": 10,
    },
    {
        "idiom_group": "gehen",
        "idiom": "zu Ende gehen",
        "phrase_cloze": "zu Ende",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "simple_verb": "enden",
        "meaning_en": "to come to an end / to draw to a close (PASSIVE)",
        "sentence_de": "Ein langes und ereignisreiches Schuljahr geht nun endlich {PHRASE}.",
        "sentence_en": "A long and eventful school year is now finally coming to an end.",
        "level": "A2",
        "grammar_notes": "Intransitive ending: 'Der Sommer geht zu Ende'.",
        "idiom_rank": 10,
    },
    {
        "idiom_group": "setzen",
        "idiom": "unter Druck setzen",
        "phrase_cloze": "unter Druck",
        "prep": "unter",
        "case": "+ Akk.",
        "case_type": "akk",
        "simple_verb": "bedrängen / zwingen",
        "meaning_en": "to put pressure on (a person or institution)",
        "sentence_de": "Der Chef setzte seine Mitarbeiter mit knappen Fristen {PHRASE}.",
        "sentence_en": "The boss put his employees under pressure with tight deadlines.",
        "level": "B1",
        "grammar_notes": "Active coercion or stress: jemanden unter Druck setzen.",
        "idiom_rank": 11,
    },
    {
        "idiom_group": "stehen",
        "idiom": "unter Druck stehen",
        "phrase_cloze": "unter Druck",
        "prep": "unter",
        "case": "+ Dat.",
        "case_type": "dat",
        "simple_verb": "gestresst sein / bedrängt werden",
        "meaning_en": "to be under pressure / to be stressed",
        "sentence_de": "Die Ärzte auf der Notaufnahme stehen ständig {PHRASE}.",
        "sentence_en": "Doctors in the emergency room are constantly under pressure.",
        "level": "B1",
        "grammar_notes": "Passive state of being stressed.",
        "idiom_rank": 11,
    },
    {
        "idiom_group": "nehmen",
        "idiom": "in Anspruch nehmen",
        "phrase_cloze": "in Anspruch",
        "prep": "in",
        "case": "+ Akk.",
        "case_type": "akk",
        "simple_verb": "beanspruchen / nutzen / fordern",
        "meaning_en": "to make use of / to take up (time or energy)",
        "sentence_de": "Die aufwendige Restaurierung wird noch viel Zeit {PHRASE} nehmen.",
        "sentence_en": "The elaborate restoration will take up a lot more time.",
        "level": "B2",
        "grammar_notes": "Very common in formal German for taking time or using a service.",
        "idiom_rank": 12,
    },
    {
        "idiom_group": "nehmen",
        "idiom": "in Betrieb nehmen",
        "phrase_cloze": "in Betrieb",
        "prep": "in",
        "case": "+ Akk.",
        "case_type": "akk",
        "simple_verb": "starten / einschalten / in Betrieb setzen",
        "meaning_en": "to put into operation / to commission (a facility or device)",
        "sentence_de": "Die Stadtwerke nahmen gestern die neue Kläranlage feierlich {PHRASE}.",
        "sentence_en": "Yesterday the municipal utilities ceremoniously commissioned the new sewage treatment plant.",
        "level": "B2",
        "grammar_notes": "Engineering and industrial commissioning.",
        "idiom_rank": 13,
    },
    {
        "idiom_group": "haben",
        "idiom": "zur Folge haben",
        "phrase_cloze": "zur Folge",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "simple_verb": "verursachen / bewirken",
        "meaning_en": "to result in / to have as a consequence",
        "sentence_de": "Der Streik des Sicherheitspersonals hatte zahlreiche Flugausfälle {PHRASE}.",
        "sentence_en": "The strike of the security staff resulted in numerous flight cancellations.",
        "level": "B2",
        "grammar_notes": "Formula: etwas (Akk) zur Folge haben.",
        "idiom_rank": 14,
    },
    {
        "idiom_group": "kommen",
        "idiom": "zu Wort kommen",
        "phrase_cloze": "zu Wort",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "simple_verb": "sprechen dürfen",
        "meaning_en": "to get a chance to speak / to have one's say",
        "sentence_de": "In der hitzigen Debatte kam der jüngste Abgeordnete kaum {PHRASE}.",
        "sentence_en": "In the heated debate, the youngest deputy barely got a chance to speak.",
        "level": "B1",
        "grammar_notes": "Idiom for gaining the floor in a discussion.",
        "idiom_rank": 15,
    },
    {
        "idiom_group": "setzen",
        "idiom": "aufs Spiel setzen",
        "phrase_cloze": "aufs Spiel",
        "prep": "auf",
        "case": "+ Akk.",
        "case_type": "akk",
        "simple_verb": "riskieren",
        "meaning_en": "to put at stake / to gamble with / to risk (ACTIVE)",
        "sentence_de": "Mit diesem riskanten Manöver setzte der Fahrer sein eigenes Leben {PHRASE}.",
        "sentence_en": "With this risky maneuver, the driver put his own life at stake.",
        "level": "B2",
        "grammar_notes": "Active endangering of an asset or life.",
        "idiom_rank": 16,
    },
    {
        "idiom_group": "stehen",
        "idiom": "auf dem Spiel stehen",
        "phrase_cloze": "auf dem Spiel",
        "prep": "auf",
        "case": "+ Dat.",
        "case_type": "dat",
        "simple_verb": "in Gefahr sein",
        "meaning_en": "to be at stake / to be in jeopardy (PASSIVE)",
        "sentence_de": "Bei dieser richtungsweisenden Wahl steht die Zukunft des Landes {PHRASE}.",
        "sentence_en": "In this pivotal election, the future of the country is at stake.",
        "level": "B2",
        "grammar_notes": "Passive peril: 'etwas steht auf dem Spiel'.",
        "idiom_rank": 16,
    },
    {
        "idiom_group": "bringen",
        "idiom": "in Ordnung bringen",
        "phrase_cloze": "in Ordnung",
        "prep": "in",
        "case": "+ Akk.",
        "case_type": "akk",
        "simple_verb": "reparieren / regeln",
        "meaning_en": "to put in order / to fix / to straighten out",
        "sentence_de": "Mach dir keine Sorgen, wir werden das Missgeschick schon wieder {PHRASE} bringen.",
        "sentence_en": "Don't worry, we will straighten out the mishap.",
        "level": "A2",
        "grammar_notes": "High frequency in everyday conversation.",
        "idiom_rank": 17,
    },
    {
        "idiom_group": "treten",
        "idiom": "in Streik treten",
        "phrase_cloze": "in Streik",
        "prep": "in",
        "case": "+ Akk.",
        "case_type": "akk",
        "simple_verb": "streiken",
        "meaning_en": "to go on strike",
        "sentence_de": "Die Lokführer traten ab Mitternacht für 48 Stunden {PHRASE}.",
        "sentence_en": "The train drivers went on strike from midnight for 48 hours.",
        "level": "B1",
        "grammar_notes": "Labor action: in Streik treten.",
        "idiom_rank": 18,
    },
    {
        "idiom_group": "bringen",
        "idiom": "zum Ausdruck bringen",
        "phrase_cloze": "zum Ausdruck",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "simple_verb": "ausdrücken / äußern",
        "meaning_en": "to express / to give voice to (ACTIVE)",
        "sentence_de": "Der Präsident brachte seine tiefe Trauer {PHRASE}.",
        "sentence_en": "The president gave expression to his deep grief.",
        "level": "B2",
        "grammar_notes": "Formal active formulation of feelings or opinions.",
        "idiom_rank": 19,
    },
    {
        "idiom_group": "kommen",
        "idiom": "zum Ausdruck kommen",
        "phrase_cloze": "zum Ausdruck",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "simple_verb": "deutlich werden / sich zeigen",
        "meaning_en": "to be expressed / to become apparent (PASSIVE)",
        "sentence_de": "In seinem poetischen Werk kommt die Liebe zur Natur stark {PHRASE}.",
        "sentence_en": "In his poetic work, love of nature is strongly expressed.",
        "level": "B2",
        "grammar_notes": "Passive manifestation.",
        "idiom_rank": 19,
    },
    {
        "idiom_group": "kommen",
        "idiom": "zu einem Entschluss kommen",
        "phrase_cloze": "zu einem Entschluss",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "simple_verb": "sich entschließen",
        "meaning_en": "to come to a decision / to make up one's mind",
        "sentence_de": "Nach reiflicher Überlegung kam der Vorstand endlich {PHRASE}.",
        "sentence_en": "After mature consideration, the board finally came to a decision.",
        "level": "B2",
        "grammar_notes": "Arriving at a firm choice.",
        "idiom_rank": 20,
    },

    # ==========================================
    # TIER 2: Advanced Fluency (B2 - C1)
    # ==========================================
    {
        "idiom_group": "ziehen",
        "idiom": "in Zweifel ziehen",
        "phrase_cloze": "in Zweifel",
        "prep": "in",
        "case": "+ Akk.",
        "case_type": "akk",
        "simple_verb": "bezweifeln",
        "meaning_en": "to call into question / to doubt (ACTIVE)",
        "sentence_de": "Niemand wagte es, die fachliche Autorität des Professors {PHRASE} zu ziehen.",
        "sentence_en": "Nobody dared to call the professor's professional authority into question.",
        "level": "B2",
        "grammar_notes": "Formula: etwas (Akk) in Zweifel ziehen.",
        "idiom_rank": 21,
    },
    {
        "idiom_group": "stehen",
        "idiom": "außer Zweifel stehen",
        "phrase_cloze": "außer Zweifel",
        "prep": "außer",
        "case": "+ Dat.",
        "case_type": "dat",
        "simple_verb": "sicher sein / unbestreitbar sein",
        "meaning_en": "to be beyond doubt / to be indisputable (PASSIVE)",
        "sentence_de": "Dass der Klimawandel vom Menschen beschleunigt wird, steht {PHRASE}.",
        "sentence_en": "That climate change is accelerated by humans is beyond doubt.",
        "level": "B2",
        "grammar_notes": "Denotes an undeniable truth.",
        "idiom_rank": 21,
    },
    {
        "idiom_group": "nehmen",
        "idiom": "zur Kenntnis nehmen",
        "phrase_cloze": "zur Kenntnis",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "simple_verb": "wahrnehmen / registrieren / beachten",
        "meaning_en": "to take note of / to acknowledge",
        "sentence_de": "Wir haben Ihre Beschwerde {PHRASE} genommen und prüfen den Sachverhalt.",
        "sentence_en": "We have taken note of your complaint and are examining the facts.",
        "level": "B1",
        "grammar_notes": "Essential formal business formula.",
        "idiom_rank": 22,
    },
    {
        "idiom_group": "setzen",
        "idiom": "in Kenntnis setzen",
        "phrase_cloze": "in Kenntnis",
        "prep": "in",
        "case": "+ Akk.",
        "case_type": "akk",
        "simple_verb": "informieren / benachrichtigen",
        "meaning_en": "to inform / to notify",
        "sentence_de": "Bitte setzen Sie mich unverzüglich {PHRASE}, sobald neue Daten vorliegen.",
        "sentence_en": "Please notify me immediately as soon as new data is available.",
        "level": "B2",
        "grammar_notes": "Formula: jemanden in Kenntnis setzen über + Akk.",
        "idiom_rank": 22,
    },
    {
        "idiom_group": "bringen",
        "idiom": "in Erfahrung bringen",
        "phrase_cloze": "in Erfahrung",
        "prep": "in",
        "case": "+ Akk.",
        "case_type": "akk",
        "simple_verb": "herausfinden / erfahren",
        "meaning_en": "to find out / to ascertain",
        "sentence_de": "Der Journalist versuchte, die geheimen Hintergründe {PHRASE} zu bringen.",
        "sentence_en": "The journalist tried to find out the secret background.",
        "level": "B2",
        "grammar_notes": "Formula: etwas (Akk) in Erfahrung bringen.",
        "idiom_rank": 23,
    },
    {
        "idiom_group": "kommen",
        "idiom": "zur Vernunft kommen",
        "phrase_cloze": "zur Vernunft",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "simple_verb": "vernünftig werden",
        "meaning_en": "to come to one's senses / to see reason",
        "sentence_de": "Hoffentlich kommt er bald {PHRASE} und beendet diesen sinnlosen Streit.",
        "sentence_en": "Hopefully he will come to his senses soon and end this senseless argument.",
        "level": "B2",
        "grammar_notes": "Behavioral turnaround: zur Vernunft kommen.",
        "idiom_rank": 24,
    },
    {
        "idiom_group": "bringen",
        "idiom": "zum Abschluss bringen",
        "phrase_cloze": "zum Abschluss",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "simple_verb": "abschließen / beenden",
        "meaning_en": "to conclude / to bring to completion",
        "sentence_de": "Nach jahrelangen Verhandlungen brachten die Diplomaten den Vertrag {PHRASE}.",
        "sentence_en": "After years of negotiations, diplomats brought the treaty to a conclusion.",
        "level": "B2",
        "grammar_notes": "Active completion of formal contracts/projects.",
        "idiom_rank": 25,
    },
    {
        "idiom_group": "stellen",
        "idiom": "in Aussicht stellen",
        "phrase_cloze": "in Aussicht",
        "prep": "in",
        "case": "+ Akk.",
        "case_type": "akk",
        "simple_verb": "versprechen / ankündigen",
        "meaning_en": "to hold out the prospect of / to promise",
        "sentence_de": "Der Abteilungsleiter stellte ihm für das nächste Jahr eine Beförderung {PHRASE}.",
        "sentence_en": "The department head held out the prospect of a promotion for him next year.",
        "level": "B2",
        "grammar_notes": "Formula: jemandem (Dat) etwas (Akk) in Aussicht stellen.",
        "idiom_rank": 26,
    },
    {
        "idiom_group": "ziehen",
        "idiom": "zur Verantwortung ziehen",
        "phrase_cloze": "zur Verantwortung",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "simple_verb": "verantwortlich machen / bestrafen",
        "meaning_en": "to hold accountable / to hold responsible",
        "sentence_de": "Die Verantwortlichen für den Skandal müssen vor Gericht {PHRASE} gezogen werden.",
        "sentence_en": "Those responsible for the scandal must be held accountable in court.",
        "level": "B2",
        "grammar_notes": "Formula: jemanden zur Verantwortung ziehen.",
        "idiom_rank": 27,
    },
    {
        "idiom_group": "umsetzen",
        "idiom": "in die Tat umsetzen",
        "phrase_cloze": "in die Tat",
        "prep": "in",
        "case": "+ Akk.",
        "case_type": "akk",
        "simple_verb": "verwirklichen / realisieren",
        "meaning_en": "to put into practice / to implement / to realize",
        "sentence_de": "Es reicht nicht, gute Ideen zu haben, man muss sie auch {PHRASE} umsetzen.",
        "sentence_en": "It is not enough to have good ideas, one must also put them into practice.",
        "level": "B2",
        "grammar_notes": "Formula: Pläne / Ideen in die Tat umsetzen.",
        "idiom_rank": 28,
    },
    {
        "idiom_group": "kommen",
        "idiom": "zu Schaden kommen",
        "phrase_cloze": "zu Schaden",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "simple_verb": "verletzt werden / Schaden erleiden",
        "meaning_en": "to come to harm / to suffer injury or damage",
        "sentence_de": "Glücklicherweise kam bei dem Brand im Schulgebäude niemand {PHRASE}.",
        "sentence_en": "Fortunately, nobody came to harm in the fire in the school building.",
        "level": "B2",
        "grammar_notes": "Formula: (nicht) zu Schaden kommen.",
        "idiom_rank": 29,
    },
    {
        "idiom_group": "fallen",
        "idiom": "zur Last fallen",
        "phrase_cloze": "zur Last",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "simple_verb": "belasten / eine Bürde sein",
        "meaning_en": "to become a burden to someone",
        "sentence_de": "Die alte Dame wollte ihren erwachsenen Kindern keinesfalls {PHRASE} fallen.",
        "sentence_en": "The old lady by no means wanted to become a burden to her adult children.",
        "level": "B2",
        "grammar_notes": "Formula: jemandem (Dat) zur Last fallen.",
        "idiom_rank": 30,
    },
    {
        "idiom_group": "stehen",
        "idiom": "in Widerspruch stehen zu",
        "phrase_cloze": "in Widerspruch",
        "prep": "in",
        "case": "+ Dat.",
        "case_type": "dat",
        "simple_verb": "widersprechen",
        "meaning_en": "to be in contradiction with / to conflict with",
        "sentence_de": "Diese Aussage steht in klarem {PHRASE} zu den früheren Zeugenaussagen.",
        "sentence_en": "This statement is in clear contradiction to earlier witness testimonies.",
        "level": "B2",
        "grammar_notes": "Logical or factual clash: in Widerspruch stehen zu + Dat.",
        "idiom_rank": 31,
    },
    {
        "idiom_group": "nehmen",
        "idiom": "Einfluss nehmen auf",
        "phrase_cloze": "Einfluss nehmen",
        "prep": "auf",
        "case": "+ Akk.",
        "case_type": "akk",
        "simple_verb": "beeinflussen",
        "meaning_en": "to exert influence on / to influence",
        "sentence_de": "Lobbyisten versuchten massiv, {PHRASE} auf die Gesetzgebung zu nehmen.",
        "sentence_en": "Lobbyists tried massively to exert influence on legislation.",
        "level": "B2",
        "grammar_notes": "Elevated synonym for 'beeinflussen'. Takes 'auf + Akkusativ'.",
        "idiom_rank": 32,
    },
    {
        "idiom_group": "nehmen",
        "idiom": "in Schutz nehmen",
        "phrase_cloze": "in Schutz",
        "prep": "in",
        "case": "+ Akk.",
        "case_type": "akk",
        "simple_verb": "verteidigen / schützen",
        "meaning_en": "to defend / to stand up for (someone facing criticism)",
        "sentence_de": "Die Mutter nahm ihren Sohn vor den ungerechten Anschuldigungen {PHRASE}.",
        "sentence_en": "The mother defended her son against the unfair accusations.",
        "level": "B2",
        "grammar_notes": "Formula: jemanden in Schutz nehmen vor + Dat.",
        "idiom_rank": 33,
    },
    {
        "idiom_group": "kommen",
        "idiom": "zur Ruhe kommen",
        "phrase_cloze": "zur Ruhe",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "simple_verb": "sich beruhigen / entspannen",
        "meaning_en": "to settle down / to find peace / to wind down",
        "sentence_de": "Nach einem hektischen Arbeitstag möchte er abends einfach nur {PHRASE} kommen.",
        "sentence_en": "After a hectic workday, in the evening he just wants to settle down.",
        "level": "A2",
        "grammar_notes": "Finding calm: zur Ruhe kommen.",
        "idiom_rank": 34,
    },
    {
        "idiom_group": "stellen",
        "idiom": "in Rechnung stellen",
        "phrase_cloze": "in Rechnung",
        "prep": "in",
        "case": "+ Akk.",
        "case_type": "akk",
        "simple_verb": "berechnen / fakturieren",
        "meaning_en": "to charge / to invoice for",
        "sentence_de": "Die erbrachten Reparaturleistungen werden dem Auftraggeber {PHRASE} gestellt.",
        "sentence_en": "The repair services rendered will be invoiced to the client.",
        "level": "B2",
        "grammar_notes": "Business/accounting phrase: jemandem etwas in Rechnung stellen.",
        "idiom_rank": 35,
    },
    {
        "idiom_group": "nehmen",
        "idiom": "in Empfang nehmen",
        "phrase_cloze": "in Empfang",
        "prep": "in",
        "case": "+ Akk.",
        "case_type": "akk",
        "simple_verb": "empfangen / annehmen",
        "meaning_en": "to receive / to take delivery of (guests, packages, awards)",
        "sentence_de": "Die Preisträgerin nahm die Auszeichnung stolz {PHRASE}.",
        "sentence_en": "The award winner proudly received the distinction.",
        "level": "B2",
        "grammar_notes": "Formal reception: etwas in Empfang nehmen.",
        "idiom_rank": 36,
    },
    {
        "idiom_group": "stehen",
        "idiom": "unter Verdacht stehen",
        "phrase_cloze": "unter Verdacht",
        "prep": "unter",
        "case": "+ Dat.",
        "case_type": "dat",
        "simple_verb": "verdächtigt werden",
        "meaning_en": "to be under suspicion of",
        "sentence_de": "Der ehemalige Buchhalter steht {PHRASE}, Firmengelder veruntreut zu haben.",
        "sentence_en": "The former accountant is under suspicion of having embezzled company funds.",
        "level": "B2",
        "grammar_notes": "Criminal/legal context: unter Verdacht stehen.",
        "idiom_rank": 37,
    },
    {
        "idiom_group": "bringen",
        "idiom": "in Sicherheit bringen",
        "phrase_cloze": "in Sicherheit",
        "prep": "in",
        "case": "+ Akk.",
        "case_type": "akk",
        "simple_verb": "retten / evakuieren",
        "meaning_en": "to bring to safety / to rescue",
        "sentence_de": "Die Rettungskräfte brachten die Bewohner des brennenden Hauses rasch {PHRASE}.",
        "sentence_en": "The emergency services quickly brought the residents of the burning house to safety.",
        "level": "B1",
        "grammar_notes": "Formula: sich / jemanden in Sicherheit bringen.",
        "idiom_rank": 38,
    },
    {
        "idiom_group": "rufen",
        "idiom": "ins Leben rufen",
        "phrase_cloze": "ins Leben",
        "prep": "in",
        "case": "+ Akk.",
        "case_type": "akk",
        "simple_verb": "gründen / initiieren",
        "meaning_en": "to found / to bring into being / to initiate (an organization, project)",
        "sentence_de": "Die engagierten Bürger riefen eine Initiative gegen Lebensmittelverschwendung {PHRASE}.",
        "sentence_en": "The dedicated citizens brought an initiative against food waste into being.",
        "level": "B2",
        "grammar_notes": "Formula: eine Initiative / ein Projekt ins Leben rufen.",
        "idiom_rank": 39,
    },
    {
        "idiom_group": "kommen",
        "idiom": "in Gang kommen",
        "phrase_cloze": "in Gang",
        "prep": "in",
        "case": "+ Akk.",
        "case_type": "akk",
        "simple_verb": "anlaufen / starten",
        "meaning_en": "to get going / to get under way",
        "sentence_de": "Nach den anfänglichen Verzögerungen kommt der Verkauf nun endlich {PHRASE}.",
        "sentence_en": "After initial delays, sales are now finally getting under way.",
        "level": "B2",
        "grammar_notes": "Intransitive start. Active form: 'etwas in Gang setzen'.",
        "idiom_rank": 40,
    },
    {
        "idiom_group": "setzen",
        "idiom": "in Gang setzen",
        "phrase_cloze": "in Gang",
        "prep": "in",
        "case": "+ Akk.",
        "case_type": "akk",
        "simple_verb": "starten / in Bewegung setzen",
        "meaning_en": "to set in motion / to trigger",
        "sentence_de": "Der Beschluss setzte eine ganze Kette von weitreichenden Ereignissen {PHRASE}.",
        "sentence_en": "The resolution set a whole chain of far-reaching events in motion.",
        "level": "B2",
        "grammar_notes": "Active triggering of a process.",
        "idiom_rank": 40,
    },
]
