"""
Curated database of the most frequent German nouns with prepositions (Nomen mit Präpositionen).
Organized by frequency and CEFR level (A1 to C1).

Every entry includes:
- noun_group: Base noun for grouping related combinations
- noun: Full noun with definite article (e.g. 'die Angst', 'das Interesse')
- prep: The required preposition
- case: "+ Akk.", "+ Dat.", "+ Gen."
- case_type: "akk", "dat", "gen"
- meaning_en: Meaning of this noun + preposition combination
- sentence_de: German example sentence with {PREP} placeholder
- sentence_en: English translation of sentence
- question_structure: Da-/Wo- compound for things and prepositional question for people
- level: CEFR level (A1, A2, B1, B2, C1)
- grammar_notes: Practical usage advice, derivation from verbs/adjectives, contrast
- noun_rank: Relative frequency rank
"""

RAW_NOUN_DATA = [
    # ==========================================
    # TIER 1: Foundational Nouns (A1 - A2)
    # ==========================================
    {
        "noun_group": "Angst",
        "noun": "die Angst",
        "prep": "vor",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "fear of / anxiety about",
        "sentence_de": "Viele Kinder haben große Angst {PREP} der Dunkelheit.",
        "sentence_en": "Many children have great fear of the dark.",
        "question_structure": "Wovor? • Davor / Vor wem?",
        "level": "A1",
        "grammar_notes": "Corresponds to 'sich fürchten vor + Dat'. Always takes 'vor + Dativ'.",
        "noun_rank": 1,
    },
    {
        "noun_group": "Hoffnung",
        "noun": "die Hoffnung",
        "prep": "auf",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "hope for",
        "sentence_de": "Die Patienten haben noch immer berechtigte Hoffnung {PREP} eine baldige Genesung.",
        "sentence_en": "The patients still have justified hope for a speedy recovery.",
        "question_structure": "Worauf? • Darauf",
        "level": "A2",
        "grammar_notes": "Corresponds to 'hoffen auf + Akk'. Always takes 'auf + Akkusativ'.",
        "noun_rank": 2,
    },
    {
        "noun_group": "Interesse",
        "noun": "das Interesse",
        "prep": "an",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "interest in (a field, topic, or person)",
        "sentence_de": "Das allgemeine Interesse {PREP} erneuerbaren Energien wächst rasant.",
        "sentence_en": "General interest in renewable energy is growing rapidly.",
        "question_structure": "Woran? • Daran",
        "level": "A2",
        "grammar_notes": "Corresponds to 'interessiert sein an + Dat'. Takes 'an + Dativ'.",
        "noun_rank": 3,
    },
    {
        "noun_group": "Interesse",
        "noun": "das Interesse",
        "prep": "für",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "interest for / passion for",
        "sentence_de": "Sein großes Interesse {PREP} fremde Sprachen zeigte sich schon früh.",
        "sentence_en": "His great interest for foreign languages showed itself early.",
        "question_structure": "Wofür? • Dafür",
        "level": "B1",
        "grammar_notes": "Corresponds to 'sich interessieren für + Akk'. Takes 'für + Akkusativ'.",
        "noun_rank": 3,
    },
    {
        "noun_group": "Freude",
        "noun": "die Freude",
        "prep": "auf",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "joy of anticipation / looking forward to (FUTURE event)",
        "sentence_de": "Die Vorfreude und Freude {PREP} das bevorstehende Weihnachtsfest war riesig.",
        "sentence_en": "The anticipation and joy for the upcoming Christmas celebration was huge.",
        "question_structure": "Worauf? • Darauf",
        "level": "A2",
        "grammar_notes": "Future anticipation: corresponds to 'sich freuen auf + Akk'.",
        "noun_rank": 4,
    },
    {
        "noun_group": "Freude",
        "noun": "die Freude",
        "prep": "über",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "gladness about / pleasure in (PRESENT/PAST event or gift)",
        "sentence_de": "Die Freude {PREP} das unerwartete Geschenk stand ihm ins Gesicht geschrieben.",
        "sentence_en": "The joy about the unexpected gift was written all over his face.",
        "question_structure": "Worüber? • Darüber",
        "level": "A2",
        "grammar_notes": "Reaction to present/past: corresponds to 'sich freuen über + Akk'.",
        "noun_rank": 4,
    },
    {
        "noun_group": "Freude",
        "noun": "die Freude",
        "prep": "an",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "enjoyment in / pleasure derived from (an activity or hobby)",
        "sentence_de": "Er hat die Freude {PREP} der täglichen Musikarbeit nie verloren.",
        "sentence_en": "He never lost the pleasure in his daily musical work.",
        "question_structure": "Woran? • Daran",
        "level": "B1",
        "grammar_notes": "Deriving joy from doing something (Freude haben an + Dat).",
        "noun_rank": 4,
    },
    {
        "noun_group": "Frage",
        "noun": "die Frage",
        "prep": "nach",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "question about / inquiry regarding",
        "sentence_de": "Die Frage {PREP} dem Sinn des Lebens beschäftigt Philosophen seit Jahrtausenden.",
        "sentence_en": "The question about the meaning of life has occupied philosophers for millennia.",
        "question_structure": "Wonach? • Danach",
        "level": "A2",
        "grammar_notes": "Corresponds to 'fragen nach + Dat'. Always 'nach + Dativ'.",
        "noun_rank": 5,
    },
    {
        "noun_group": "Antwort",
        "noun": "die Antwort",
        "prep": "auf",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "answer to / response to",
        "sentence_de": "Die Antwort {PREP} diese schwierige Frage blieb er uns schuldig.",
        "sentence_en": "He remained indebted to us for the answer to this difficult question.",
        "question_structure": "Worauf? • Darauf",
        "level": "A1",
        "grammar_notes": "Corresponds to 'antworten auf + Akk'. Always 'auf + Akkusativ'.",
        "noun_rank": 6,
    },
    {
        "noun_group": "Bitte",
        "noun": "die Bitte",
        "prep": "um",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "request for",
        "sentence_de": "Seine Bitte {PREP} finanzielle Unterstützung wurde wohlwollend geprüft.",
        "sentence_en": "His request for financial support was benevolently examined.",
        "question_structure": "Worum? • Darum",
        "level": "A2",
        "grammar_notes": "Corresponds to 'bitten um + Akk'.",
        "noun_rank": 7,
    },
    {
        "noun_group": "Dank",
        "noun": "der Dank",
        "prep": "für",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "gratitude for / thanks for",
        "sentence_de": "Als Dank {PREP} die Einladung brachte sie einen herrlichen Blumenstrauß mit.",
        "sentence_en": "As thanks for the invitation, she brought along a wonderful bouquet of flowers.",
        "question_structure": "Wofür? • Dafür",
        "level": "A1",
        "grammar_notes": "Corresponds to 'danken für + Akk'.",
        "noun_rank": 8,
    },
    {
        "noun_group": "Glückwunsch",
        "noun": "der Glückwunsch",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "congratulations on",
        "sentence_de": "Herzlichen Glückwunsch {PREP} deinem heutigen Geburtstag!",
        "sentence_en": "Warm congratulations on your birthday today!",
        "question_structure": "Wozu? • Dazu",
        "level": "A1",
        "grammar_notes": "Corresponds to 'gratulieren zu + Dat'. Always 'zu + Dativ'.",
        "noun_rank": 9,
    },
    {
        "noun_group": "Einladung",
        "noun": "die Einladung",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "invitation to",
        "sentence_de": "Vielen Dank für die freundliche Einladung {PREP} deiner Hochzeit.",
        "sentence_en": "Thank you very much for the kind invitation to your wedding.",
        "question_structure": "Wozu? • Dazu",
        "level": "A1",
        "grammar_notes": "Corresponds to 'einladen zu + Dat'.",
        "noun_rank": 10,
    },

    # ==========================================
    # TIER 2: Essential Intermediate (B1)
    # ==========================================
    {
        "noun_group": "Zweifel",
        "noun": "der Zweifel",
        "prep": "an",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "doubt about",
        "sentence_de": "Es gibt berechtigte Zweifel {PREP} der Glaubwürdigkeit des Zeugen.",
        "sentence_en": "There are justified doubts about the witness's credibility.",
        "question_structure": "Woran? • Daran",
        "level": "B1",
        "grammar_notes": "Corresponds to 'zweifeln an + Dat'. Always 'an + Dativ'.",
        "noun_rank": 11,
    },
    {
        "noun_group": "Kritik",
        "noun": "die Kritik",
        "prep": "an",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "criticism of",
        "sentence_de": "Die scharfe Kritik {PREP} den neuen Sparmaßnahmen war unüberhörbar.",
        "sentence_en": "The sharp criticism of the new austerity measures was unmistakable.",
        "question_structure": "Woran? • Daran / An wem?",
        "level": "B1",
        "grammar_notes": "Formula: Kritik an + Dat üben (to level criticism at).",
        "noun_rank": 12,
    },
    {
        "noun_group": "Erinnerung",
        "noun": "die Erinnerung",
        "prep": "an",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "memory of / reminder of",
        "sentence_de": "Die lebendige Erinnerung {PREP} diesen Sommertag verblasste nie.",
        "sentence_en": "The vivid memory of that summer day never faded.",
        "question_structure": "Woran? • Daran / An wen?",
        "level": "B1",
        "grammar_notes": "Corresponds to 'sich erinnern an + Akk'. Always 'an + Akkusativ'.",
        "noun_rank": 13,
    },
    {
        "noun_group": "Suche",
        "noun": "die Suche",
        "prep": "nach",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "search for / quest for",
        "sentence_de": "Die Ermittler sind fieberhaft auf der Suche {PREP} neuen Spuren.",
        "sentence_en": "The investigators are feverishly on the search for new clues.",
        "question_structure": "Wonach? • Danach",
        "level": "A2",
        "grammar_notes": "Formula: auf der Suche nach + Dat sein. Corresponds to 'suchen nach'.",
        "noun_rank": 14,
    },
    {
        "noun_group": "Glaube",
        "noun": "der Glaube",
        "prep": "an",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "faith in / belief in",
        "sentence_de": "Sein unerschütterlicher Glaube {PREP} den Sieg gab der Mannschaft Kraft.",
        "sentence_en": "His unshakeable faith in victory gave the team strength.",
        "question_structure": "Woran? • Daran / An wen?",
        "level": "B1",
        "grammar_notes": "Corresponds to 'glauben an + Akk'.",
        "noun_rank": 15,
    },
    {
        "noun_group": "Furcht",
        "noun": "die Furcht",
        "prep": "vor",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "dread of / fear of",
        "sentence_de": "Aus Furcht {PREP} möglichen Konsequenzen schwieg er beharrlich.",
        "sentence_en": "Out of fear of possible consequences, he remained stubbornly silent.",
        "question_structure": "Wovor? • Davor",
        "level": "B1",
        "grammar_notes": "Corresponds to 'sich fürchten vor + Dat'. Elevated synonym of 'Angst vor'.",
        "noun_rank": 16,
    },
    {
        "noun_group": "Entscheidung",
        "noun": "die Entscheidung",
        "prep": "für",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "decision in favor of",
        "sentence_de": "Ihre bewusste Entscheidung {PREP} diesen Beruf hat sie nie bereut.",
        "sentence_en": "She never regretted her conscious decision in favor of this profession.",
        "question_structure": "Wofür? • Dafür",
        "level": "B1",
        "grammar_notes": "Corresponds to 'sich entscheiden für + Akk'.",
        "noun_rank": 17,
    },
    {
        "noun_group": "Entscheidung",
        "noun": "die Entscheidung",
        "prep": "gegen",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "decision against",
        "sentence_de": "Die Entscheidung {PREP} den Neubau stieß auf breite Zustimmung.",
        "sentence_en": "The decision against the new building met with broad approval.",
        "question_structure": "Wogegen? • Dagegen",
        "level": "B1",
        "grammar_notes": "Corresponds to 'sich entscheiden gegen + Akk'.",
        "noun_rank": 17,
    },
    {
        "noun_group": "Entschuldigung",
        "noun": "die Entschuldigung",
        "prep": "für",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "apology for (a mistake or delay)",
        "sentence_de": "Er überreichte ihr eine schriftliche Entschuldigung {PREP} sein Fehlverhalten.",
        "sentence_en": "He handed her a written apology for his misconduct.",
        "question_structure": "Wofür? • Dafür",
        "level": "A2",
        "grammar_notes": "The reason takes 'für + Akkusativ'.",
        "noun_rank": 18,
    },
    {
        "noun_group": "Verständnis",
        "noun": "das Verständnis",
        "prep": "für",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "understanding for / sympathy with",
        "sentence_de": "Wir bitten alle Fahrgäste um Verständnis {PREP} die Unannehmlichkeiten.",
        "sentence_en": "We ask all passengers for understanding for the inconveniences.",
        "question_structure": "Wofür? • Dafür",
        "level": "B1",
        "grammar_notes": "Formula: Verständnis für etwas haben/bitten.",
        "noun_rank": 19,
    },
    {
        "noun_group": "Rücksicht",
        "noun": "die Rücksicht",
        "prep": "auf",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "consideration for / regard for",
        "sentence_de": "Aus Rücksicht {PREP} die schlafenden Nachbarn machten wir die Musik leiser.",
        "sentence_en": "Out of consideration for the sleeping neighbors, we turned the music down.",
        "question_structure": "Worauf? • Darauf / Auf wen?",
        "level": "B1",
        "grammar_notes": "Idiom: Rücksicht auf jemanden/etwas nehmen.",
        "noun_rank": 20,
    },
    {
        "noun_group": "Vertrauen",
        "noun": "das Vertrauen",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "trust in / confidence towards (a PERSON)",
        "sentence_de": "Die Patienten haben großes Vertrauen {PREP} ihrem behandelnden Arzt.",
        "sentence_en": "The patients have great trust in their attending physician.",
        "question_structure": "Zu wem?",
        "level": "B1",
        "grammar_notes": "Interpersonal trust in someone: 'zu + Dativ'.",
        "noun_rank": 21,
    },
    {
        "noun_group": "Vertrauen",
        "noun": "das Vertrauen",
        "prep": "auf",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "reliance on / confidence in (abilities, divine help)",
        "sentence_de": "Ihr festes Vertrauen {PREP} die eigene Stärke half ihr durch die Krise.",
        "sentence_en": "Her firm trust in her own strength helped her through the crisis.",
        "question_structure": "Worauf? • Darauf",
        "level": "B1",
        "grammar_notes": "Faith in a principle or capability: 'auf + Akkusativ'.",
        "noun_rank": 21,
    },
    {
        "noun_group": "Misstrauen",
        "noun": "das Misstrauen",
        "prep": "gegenüber",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "distrust towards / suspicion of",
        "sentence_de": "Sein tiefes Misstrauen {PREP} fremden Personen gegenüber war spürbar.",
        "sentence_en": "His deep distrust towards strangers was palpable.",
        "question_structure": "Gegenüber wem?",
        "level": "B1",
        "grammar_notes": "Takes 'gegenüber + Dativ'.",
        "noun_rank": 22,
    },
    {
        "noun_group": "Abhängigkeit",
        "noun": "die Abhängigkeit",
        "prep": "von",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "dependence on / addiction to",
        "sentence_de": "Die wirtschaftliche Abhängigkeit {PREP} fossilen Brennstoffen soll sinken.",
        "sentence_en": "Economic dependence on fossil fuels is intended to decrease.",
        "question_structure": "Wovon? • Davon",
        "level": "B1",
        "grammar_notes": "Corresponds to 'abhängen von + Dat'.",
        "noun_rank": 23,
    },
    {
        "noun_group": "Begeisterung",
        "noun": "die Begeisterung",
        "prep": "für",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "enthusiasm for / passion for",
        "sentence_de": "Ihre Begeisterung {PREP} klassische Literatur war regelrecht ansteckend.",
        "sentence_en": "Her enthusiasm for classical literature was downright infectious.",
        "question_structure": "Wofür? • Dafür",
        "level": "B1",
        "grammar_notes": "Takes 'für + Akkusativ' (or 'von + Dat' when referring to a specific performance).",
        "noun_rank": 24,
    },
    {
        "noun_group": "Bereitschaft",
        "noun": "die Bereitschaft",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "willingness to / readiness for",
        "sentence_de": "Die Bereitschaft {PREP} einem konstruktiven Dialog ist auf beiden Seiten da.",
        "sentence_en": "The readiness for a constructive dialogue is present on both sides.",
        "question_structure": "Wozu? • Dazu",
        "level": "B1",
        "grammar_notes": "Corresponds to 'bereit sein zu + Dat'.",
        "noun_rank": 25,
    },
    {
        "noun_group": "Bericht",
        "noun": "der Bericht",
        "prep": "über",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "report on / account of",
        "sentence_de": "Der ausführliche Bericht {PREP} die Konferenz erschien heute Morgen.",
        "sentence_en": "The detailed report on the conference appeared this morning.",
        "question_structure": "Worüber? • Darüber",
        "level": "A2",
        "grammar_notes": "Corresponds to 'berichten über + Akk'.",
        "noun_rank": 26,
    },
    {
        "noun_group": "Bewerbung",
        "noun": "die Bewerbung",
        "prep": "um",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "application for (a position or grant)",
        "sentence_de": "Ihre Bewerbung {PREP} die freie Leitungsstelle war von Erfolg gekrönt.",
        "sentence_en": "Her application for the vacant management position was crowned with success.",
        "question_structure": "Worum? • Darum",
        "level": "B1",
        "grammar_notes": "Target role takes 'um + Akkusativ'.",
        "noun_rank": 27,
    },
    {
        "noun_group": "Beziehung",
        "noun": "die Beziehung",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "relationship with / connection to",
        "sentence_de": "Er pflegt seit vielen Jahren eine enge Beziehung {PREP} seinen Nachbarn.",
        "sentence_en": "For many years he has maintained a close relationship with his neighbors.",
        "question_structure": "Zu wem? / Wozu?",
        "level": "B1",
        "grammar_notes": "Interpersonal relationship takes 'zu + Dativ'.",
        "noun_rank": 28,
    },
    {
        "noun_group": "Diskussion",
        "noun": "die Diskussion",
        "prep": "über",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "discussion about / debate on",
        "sentence_de": "Die hitzige Diskussion {PREP} das Rauchverbot dauerte mehrere Stunden.",
        "sentence_en": "The heated discussion about the smoking ban lasted several hours.",
        "question_structure": "Worüber? • Darüber",
        "level": "A2",
        "grammar_notes": "Topic of discussion takes 'über + Akkusativ'.",
        "noun_rank": 29,
    },
    {
        "noun_group": "Eifersucht",
        "noun": "die Eifersucht",
        "prep": "auf",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "jealousy of",
        "sentence_de": "Seine unkontrollierte Eifersucht {PREP} ihre Kollegen zerstörte die Partnerschaft.",
        "sentence_en": "His uncontrolled jealousy of her colleagues destroyed the partnership.",
        "question_structure": "Auf wen?",
        "level": "B1",
        "grammar_notes": "Corresponds to 'eifersüchtig auf + Akk'.",
        "noun_rank": 30,
    },
    {
        "noun_group": "Neid",
        "noun": "der Neid",
        "prep": "auf",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "envy of (possessions or success)",
        "sentence_de": "Aus Neid {PREP} seinen beruflichen Erfolg verbreitete man böse Gerüchte.",
        "sentence_en": "Out of envy of his professional success, malicious rumors were spread.",
        "question_structure": "Worauf? • Darauf / Auf wen?",
        "level": "B1",
        "grammar_notes": "Corresponds to 'neidisch auf + Akk'.",
        "noun_rank": 31,
    },

    # ==========================================
    # TIER 3: Advanced Nouns (B2 - C1)
    # ==========================================
    {
        "noun_group": "Fähigkeit",
        "noun": "die Fähigkeit",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "ability to / capability of",
        "sentence_de": "Die Fähigkeit {PREP} kritischem Denken ist eine Grundvoraussetzung für die Wissenschaft.",
        "sentence_en": "The ability for critical thinking is a fundamental prerequisite for science.",
        "question_structure": "Wozu? • Dazu",
        "level": "B2",
        "grammar_notes": "Corresponds to 'fähig sein zu + Dat'.",
        "noun_rank": 32,
    },
    {
        "noun_group": "Geduld",
        "noun": "die Geduld",
        "prep": "mit",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "patience with",
        "sentence_de": "Der junge Lehrer bewies bewundernswerte Geduld {PREP} den unruhigen Schülern.",
        "sentence_en": "The young teacher proved admirable patience with the restless pupils.",
        "question_structure": "Mit wem? / Womit?",
        "level": "B1",
        "grammar_notes": "Takes 'mit + Dativ'.",
        "noun_rank": 33,
    },
    {
        "noun_group": "Gelegenheit",
        "noun": "die Gelegenheit",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "opportunity for / chance to",
        "sentence_de": "Nutzen Sie bei der Konferenz die einmalige Gelegenheit {PREP} neuen Kontakten!",
        "sentence_en": "At the conference, seize the unique opportunity for new contacts!",
        "question_structure": "Wozu? • Dazu",
        "level": "B1",
        "grammar_notes": "Often combined with an infinitive clause: 'Gelegenheit haben zu + Inf'.",
        "noun_rank": 34,
    },
    {
        "noun_group": "Gewöhnung",
        "noun": "die Gewöhnung",
        "prep": "an",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "habituation to / acclimatization to",
        "sentence_de": "Die Gewöhnung {PREP} das ungewohnte Schichtarbeitssystem dauert oft Wochen.",
        "sentence_en": "Acclimatization to the unfamiliar shift work system often takes weeks.",
        "question_structure": "Woran? • Daran",
        "level": "B2",
        "grammar_notes": "Corresponds to 'sich gewöhnen an + Akk'.",
        "noun_rank": 35,
    },
    {
        "noun_group": "Grund",
        "noun": "der Grund",
        "prep": "für",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "reason for / cause of",
        "sentence_de": "Es gibt bisher keinen ersichtlichen Grund {PREP} diese drastische Maßnahme.",
        "sentence_en": "There is so far no apparent reason for this drastic measure.",
        "question_structure": "Wofür? • Dafür",
        "level": "A2",
        "grammar_notes": "Takes 'für + Akkusativ'.",
        "noun_rank": 36,
    },
    {
        "noun_group": "Hinweis",
        "noun": "der Hinweis",
        "prep": "auf",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "clue to / reference to / pointer toward",
        "sentence_de": "Die Ermittler fanden einen entscheidenden Hinweis {PREP} den Aufenthaltsort des Täters.",
        "sentence_en": "Investigators found a decisive clue to the whereabouts of the perpetrator.",
        "question_structure": "Worauf? • Darauf",
        "level": "B1",
        "grammar_notes": "Corresponds to 'hinweisen auf + Akk'.",
        "noun_rank": 37,
    },
    {
        "noun_group": "Kampf",
        "noun": "der Kampf",
        "prep": "gegen",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "fight against / struggle against",
        "sentence_de": "Der weltweite Kampf {PREP} die Armut erfordert gemeinsame Anstrengungen.",
        "sentence_en": "The global fight against poverty requires joint efforts.",
        "question_structure": "Wogegen? • Dagegen / Gegen wen?",
        "level": "B1",
        "grammar_notes": "Corresponds to 'kämpfen gegen + Akk'.",
        "noun_rank": 38,
    },
    {
        "noun_group": "Kampf",
        "noun": "der Kampf",
        "prep": "für",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "fight for / struggle for (rights, freedom)",
        "sentence_de": "Ihr unermüdlicher Kampf {PREP} Bürgerrechte inspirierte Generationen.",
        "sentence_en": "Her tireless fight for civil rights inspired generations.",
        "question_structure": "Wofür? • Dafür",
        "level": "B1",
        "grammar_notes": "Corresponds to 'kämpfen für + Akk'.",
        "noun_rank": 38,
    },
    {
        "noun_group": "Kampf",
        "noun": "der Kampf",
        "prep": "um",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "struggle for / fight over (survival, power, custody)",
        "sentence_de": "Der erbitterte Kampf {PREP} die politische Macht spitzt sich weiter zu.",
        "sentence_en": "The bitter struggle for political power continues to intensify.",
        "question_structure": "Worum? • Darum",
        "level": "B2",
        "grammar_notes": "Corresponds to 'kämpfen um + Akk'.",
        "noun_rank": 38,
    },
    {
        "noun_group": "Mangel",
        "noun": "der Mangel",
        "prep": "an",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "lack of / deficiency in",
        "sentence_de": "In vielen Krankenhäusern herrscht akuter Mangel {PREP} qualifiziertem Pflegepersonal.",
        "sentence_en": "In many hospitals, there is an acute lack of qualified nursing staff.",
        "question_structure": "Woran? • Daran",
        "level": "B1",
        "grammar_notes": "Corresponds to 'mangeln an + Dat'. Always 'an + Dativ'.",
        "noun_rank": 39,
    },
    {
        "noun_group": "Mut",
        "noun": "der Mut",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "courage for / courage to (make a change or stand up)",
        "sentence_de": "Man braucht oft großen Mut {PREP} einer ehrlichen Veränderung im Leben.",
        "sentence_en": "One often needs great courage for an honest change in life.",
        "question_structure": "Wozu? • Dazu",
        "level": "B1",
        "grammar_notes": "Formula: Mut zu etwas (Dat) haben.",
        "noun_rank": 40,
    },
    {
        "noun_group": "Nachfrage",
        "noun": "die Nachfrage",
        "prep": "nach",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "demand for (goods or services in an economy)",
        "sentence_de": "Die weltweite Nachfrage {PREP} Elektrofahrzeugen ist sprunghaft gestiegen.",
        "sentence_en": "Global demand for electric vehicles has jumped dramatically.",
        "question_structure": "Wonach? • Danach",
        "level": "B1",
        "grammar_notes": "Economic term: Nachfrage nach + Dat (opposite of Angebot an + Dat).",
        "noun_rank": 41,
    },
    {
        "noun_group": "Angebot",
        "noun": "das Angebot",
        "prep": "an",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "supply of / range of (products, goods)",
        "sentence_de": "Der Wochenmarkt bietet ein reichhaltiges Angebot {PREP} frischem Gemüse.",
        "sentence_en": "The weekly market offers a rich supply of fresh vegetables.",
        "question_structure": "Woran? • Daran",
        "level": "B1",
        "grammar_notes": "Takes 'an + Dativ'.",
        "noun_rank": 42,
    },
    {
        "noun_group": "Neugier",
        "noun": "die Neugier",
        "prep": "auf",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "curiosity about",
        "sentence_de": "Seine unstillbare Neugier {PREP} fremde Länder trieb ihn in die Ferne.",
        "sentence_en": "His insatiable curiosity about foreign lands drove him abroad.",
        "question_structure": "Worauf? • Darauf",
        "level": "B1",
        "grammar_notes": "Corresponds to 'neugierig auf + Akk'.",
        "noun_rank": 43,
    },
    {
        "noun_group": "Protest",
        "noun": "der Protest",
        "prep": "gegen",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "protest against",
        "sentence_de": "Der lautstarke Protest {PREP} den Abriss des historischen Theaters war erfolgreich.",
        "sentence_en": "The vocal protest against the demolition of the historic theater was successful.",
        "question_structure": "Wogegen? • Dagegen / Gegen wen?",
        "level": "B1",
        "grammar_notes": "Corresponds to 'protestieren gegen + Akk'.",
        "noun_rank": 44,
    },
    {
        "noun_group": "Reaktion",
        "noun": "die Reaktion",
        "prep": "auf",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "reaction to / response to",
        "sentence_de": "Die erste Reaktion {PREP} den neuen Gesetzesentwurf fiel gespalten aus.",
        "sentence_en": "The initial reaction to the new bill turned out divided.",
        "question_structure": "Worauf? • Darauf",
        "level": "B1",
        "grammar_notes": "Corresponds to 'reagieren auf + Akk'.",
        "noun_rank": 45,
    },
    {
        "noun_group": "Schutz",
        "noun": "der Schutz",
        "prep": "vor",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "protection from / shelter against",
        "sentence_de": "Die dicke Mauer bot den Dorfbewohnern Schutz {PREP} den kalten Nordwinden.",
        "sentence_en": "The thick wall offered the villagers protection from the cold north winds.",
        "question_structure": "Wovor? • Davor",
        "level": "A2",
        "grammar_notes": "Corresponds to 'schützen vor + Dat'.",
        "noun_rank": 46,
    },
    {
        "noun_group": "Sehnsucht",
        "noun": "die Sehnsucht",
        "prep": "nach",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "longing for / yearning for",
        "sentence_de": "Im Exil überkam ihn eine unbändige Sehnsucht {PREP} den Bergen seiner Heimat.",
        "sentence_en": "In exile, an uncontrollable longing for the mountains of his homeland overcame him.",
        "question_structure": "Wonach? • Danach / Nach wem?",
        "level": "B1",
        "grammar_notes": "Corresponds to 'sich sehnen nach + Dat'. Always 'nach + Dativ'.",
        "noun_rank": 47,
    },
    {
        "noun_group": "Sorge",
        "noun": "die Sorge",
        "prep": "um",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "worry about / concern for (safety or well-being)",
        "sentence_de": "Die elterliche Sorge {PREP} das Wohl des verunglückten Kindes war grenzenlos.",
        "sentence_en": "Parental worry for the injured child's well-being was boundless.",
        "question_structure": "Worum? • Darum / Um wen?",
        "level": "B1",
        "grammar_notes": "Corresponds to 'sich sorgen um + Akk'.",
        "noun_rank": 48,
    },
    {
        "noun_group": "Sorge",
        "noun": "die Sorge",
        "prep": "für",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "care for / provision for (maintenance, custody)",
        "sentence_de": "Die finanzielle Sorge {PREP} die betagten Eltern übernahmen die Geschwister gemeinsam.",
        "sentence_en": "The siblings jointly assumed financial care for their aged parents.",
        "question_structure": "Wofür? • Dafür",
        "level": "B2",
        "grammar_notes": "Provision: 'Sorge tragen für + Akk' or 'sorgen für + Akk'.",
        "noun_rank": 48,
    },
    {
        "noun_group": "Streit",
        "noun": "der Streit",
        "prep": "über",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "quarrel / argument about (a topic)",
        "sentence_de": "Der endlose Streit {PREP} die Aufteilung des Budgets blockierte die Arbeit.",
        "sentence_en": "The endless quarrel about dividing the budget blocked work.",
        "question_structure": "Worüber? • Darüber",
        "level": "B1",
        "grammar_notes": "Topic: 'über + Akkusativ'. Corresponds to 'streiten über'.",
        "noun_rank": 49,
    },
    {
        "noun_group": "Streit",
        "noun": "der Streit",
        "prep": "um",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "dispute over / contest for (an asset or prize)",
        "sentence_de": "Der jahrelange Streit {PREP} das Erbe der wohlhabenden Tante zerriss die Familie.",
        "sentence_en": "The years-long dispute over the wealthy aunt's inheritance tore the family apart.",
        "question_structure": "Worum? • Darum",
        "level": "B1",
        "grammar_notes": "Object contested: 'um + Akkusativ'.",
        "noun_rank": 49,
    },
    {
        "noun_group": "Traum",
        "noun": "der Traum",
        "prep": "von",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "dream of / about",
        "sentence_de": "Ihr langgehegter Traum {PREP} einem eigenen Biobauernhof ging endlich in Erfüllung.",
        "sentence_en": "Her long-cherished dream of her own organic farm finally came true.",
        "question_structure": "Wovon? • Davon",
        "level": "A2",
        "grammar_notes": "Corresponds to 'träumen von + Dat'.",
        "noun_rank": 50,
    },
    {
        "noun_group": "Verantwortung",
        "noun": "die Verantwortung",
        "prep": "für",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "responsibility for",
        "sentence_de": "Der Manager übernahm die volle Verantwortung {PREP} den schweren Fehler.",
        "sentence_en": "The manager assumed full responsibility for the serious error.",
        "question_structure": "Wofür? • Dafür",
        "level": "B1",
        "grammar_notes": "Formula: die Verantwortung für etwas (Akk) tragen/übernehmen.",
        "noun_rank": 51,
    },
    {
        "noun_group": "Vergleich",
        "noun": "der Vergleich",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "comparison to / compared with",
        "sentence_de": "Im Vergleich {PREP} den Vorjahren ist der Umsatz dieses Jahr deutlich gewachsen.",
        "sentence_en": "Compared to previous years, turnover has grown significantly this year.",
        "question_structure": "Wozu? • Dazu",
        "level": "B1",
        "grammar_notes": "Fixed prepositional phrase: 'im Vergleich zu + Dativ'.",
        "noun_rank": 52,
    },
    {
        "noun_group": "Verhältnis",
        "noun": "das Verhältnis",
        "prep": "zu",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "relationship with / attitude towards (a person or group)",
        "sentence_de": "Er hat ein überaus harmonisches Verhältnis {PREP} seinen Schwiegereltern.",
        "sentence_en": "He has an exceedingly harmonious relationship with his in-laws.",
        "question_structure": "Zu wem?",
        "level": "B1",
        "grammar_notes": "Relationship towards people: takes 'zu + Dativ'.",
        "noun_rank": 53,
    },
    {
        "noun_group": "Verzicht",
        "noun": "der Verzicht",
        "prep": "auf",
        "case": "+ Akk.",
        "case_type": "akk",
        "meaning_en": "renunciation of / doing without",
        "sentence_de": "Der bewusste Verzicht {PREP} Fleisch schont die Umwelt und die Gesundheit.",
        "sentence_en": "The conscious renunciation of meat protects the environment and health.",
        "question_structure": "Worauf? • Darauf",
        "level": "B2",
        "grammar_notes": "Corresponds to 'verzichten auf + Akk'.",
        "noun_rank": 54,
    },
    {
        "noun_group": "Vorstellung",
        "noun": "die Vorstellung",
        "prep": "von",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "idea of / concept of",
        "sentence_de": "Hast du eine genaue Vorstellung {PREP} dem Arbeitsaufwand dieses Projekts?",
        "sentence_en": "Do you have an accurate idea of the workload of this project?",
        "question_structure": "Wovon? • Davon",
        "level": "A2",
        "grammar_notes": "Formula: eine Vorstellung von etwas (Dat) haben.",
        "noun_rank": 55,
    },
    {
        "noun_group": "Warnung",
        "noun": "die Warnung",
        "prep": "vor",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "warning against / warning of",
        "sentence_de": "Trotz der deutlichen Warnung {PREP} den Lawinen wagten sich die Skifahrer ins freie Gelände.",
        "sentence_en": "Despite the clear warning of avalanches, the skiers ventured into open terrain.",
        "question_structure": "Wovor? • Davor",
        "level": "B1",
        "grammar_notes": "Corresponds to 'warnen vor + Dat'. Always 'vor + Dativ'.",
        "noun_rank": 56,
    },
    {
        "noun_group": "Wunsch",
        "noun": "der Wunsch",
        "prep": "nach",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "desire for / wish for",
        "sentence_de": "Sein inniger Wunsch {PREP} Ruhe und Erholung wurde endlich wahr.",
        "sentence_en": "His heartfelt desire for peace and rest finally came true.",
        "question_structure": "Wonach? • Danach",
        "level": "A2",
        "grammar_notes": "Aspiration for a state takes 'nach + Dativ'.",
        "noun_rank": 57,
    },
    {
        "noun_group": "Zufriedenheit",
        "noun": "die Zufriedenheit",
        "prep": "mit",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "satisfaction with",
        "sentence_de": "Die allgemeine Zufriedenheit {PREP} dem neuen Produkt ist erfreulich hoch.",
        "sentence_en": "General satisfaction with the new product is gratifyingly high.",
        "question_structure": "Womit? • Damit",
        "level": "B1",
        "grammar_notes": "Corresponds to 'zufrieden mit + Dat'.",
        "noun_rank": 58,
    },
    {
        "noun_group": "Zusammenhang",
        "noun": "der Zusammenhang",
        "prep": "mit",
        "case": "+ Dat.",
        "case_type": "dat",
        "meaning_en": "connection with / correlation with",
        "sentence_de": "Gibt es einen direkten Zusammenhang {PREP} der Ernährung und der Krankheit?",
        "sentence_en": "Is there a direct connection between diet and the disease?",
        "question_structure": "Womit? • Damit",
        "level": "B2",
        "grammar_notes": "Formula: in Zusammenhang mit etwas (Dat) stehen.",
        "noun_rank": 59,
    },
]
